### ISSUE TITLE
java.util.NoSuchElementException: Param binSampleCount does not exist on LightGBM

### ISSUE THREAD

**Issue by sarmientoj24** [microsoft/SynapseML#1046]
**Describe the bug**
binSampleCount does not exist

Instantiation of LightGBM
```
model = LightGBMClassifier(featuresCol="idfFeatures", labelCol="label")
pipeline_cv_lr = Pipeline().setStages(
    [nltk_cleaner, count_vectorizer, idf, model]
)

model_cv_lr = pipeline_cv_lr.fit(train_data)
predictions_cv_lr = model_cv_lr.transform(test_data)
```

**Info (please complete the following information):**
 - MMLSpark Version: mmlspark_2.11;1.0.0-rc3 
 - Spark Version e.g. 2.4.5
 - Spark Platform: Local Jupyter

** Error**
```
Py4JJavaError: An error occurred while calling o80.getParam.
: java.util.NoSuchElementException: Param binSampleCount does not exist.
	at org.apache.spark.ml.param.Params$$anonfun$getParam$2.apply(params.scala:729)
	at org.apache.spark.ml.param.Params$$anonfun$getParam$2.apply(params.scala:729)
	at scala.Option.getOrElse(Option.scala:121)
	at org.apache.spark.ml.param.Params$class.getParam(params.scala:728)
	at org.apache.spark.ml.PipelineStage.getParam(Pipeline.scala:42)
	at sun.reflect.GeneratedMethodAccessor28.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
	at py4j.Gateway.invoke(Gateway.java:282)
	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
	at py4j.commands.CallCommand.execute(CallCommand.java:79)
	at py4j.GatewayConnection.run(GatewayConnection.java:238)
	at java.lang.Thread.run(Thread.java:748)
```

[AB#1164920](https://msdata.visualstudio.com/b9b2accc-2d1c-45b3-9d24-0eb5d78cc47f/_workitems/edit/1164920)

**Comment by imatiach-msft** [comment]
@sarmientoj24 sorry about the trouble you are having.  This looks very strange, because this parameter definitely does exist in lightgbm.  I wonder if you somehow have multiple environments installed, or your python/pyspark code is somehow not in sync with the scala/Java code.  How did you install the library in your local jupyter notebook?

**Comment by imatiach-msft** [comment]
@sarmientoj24 very strange, it should just work.  What kind of environment/cluster are you running on?  Maybe this way doesn't work there?  It is possible there are multiple mmlspark versions installed there somehow?

**Comment by Haizhuolaojisite** [comment]
@imatiach-msft I met the same error as above, and I am thinking this is due to installation issues. I have spark 3.1.2 in my local jupyter notebook, and I followed the python installation method as in this official website:
[(https://microsoft.github.io/SynapseML/)](url)

I use this code for installation as I use 3.1.2 spark:
`spark = SparkSession.builder.appName("MyApp") \
            .config("spark.jars.packages", "com.microsoft.azure:synapseml_2.12:0.9.5-13-d1b51517-SNAPSHOT") \
            .config("spark.jars.repositories", "https://mmlspark.azureedge.net/maven") \
            .getOrCreate()
`

But if failed when I run "import synapse", it said no module found. I also tried in Kaggle notebook and GCP Dataproc, both had same error. Ultimately, I had to use pip install synapseml, and pip install synapse so that I can run the LightGBM model and import this module. 

Could you please help me with this installation issue if possible? Thanks a lot!

**Comment by ranadeepsingh** [comment]
Thank you for the report. `binSampleCount` is present as a typed LightGBM parameter in current SynapseML; this failure came from an old Python/JVM artifact mismatch. Closing as resolved—please open a fresh issue if it reproduces with matching 1.1.3 artifacts.
