### ISSUE TITLE
add doc: how to config predict_disable_shape_check=true

### ISSUE THREAD

**Issue by yinrong** [microsoft/SynapseML#1159]
I can not find example or document how to config `predict_disable_shape_check=true` 
After I encounter the exception:
```
java.lang.Exception: Booster Predict call failed in LightGBM with error: The number of features in data (164725) is not the same as it was in training data (160747).
You can set ``predict_disable_shape_check=true`` to discard this error, but please be aware what you are doing.
at com.microsoft.ml.spark.lightgbm.LightGBMUtils$.validate(LightGBMUtils.scala:31)
at com.microsoft.ml.spark.lightgbm.LightGBMBooster.predictForCSR(LightGBMBooster.scala:283)
at com.microsoft.ml.spark.lightgbm.LightGBMBooster.score(LightGBMBooster.scala:207)
at com.microsoft.ml.spark.lightgbm.LightGBMClassificationModel.predictProbability(LightGBMClassifier.scala:160)
...
```

I tried
```
LightGBMClassificationModel.loadNativeModelFromFile(“/path/to/model.txt")
        .set(new BooleanParam("", "predict_disable_shape_check", ""), true)
```
no working

Please give an example or document for
```
LightGBMClassificationModel.loadNativeModelFromFile(“/path/to/model.txt")
    .set("predict_disable_shape_check", true)
```

**Comment by yinrong** [comment]
I work around this by slicing my features columns before model prediction.
