### ISSUE TITLE
Cannot install using spark-shell: [unresolved dependency: com.microsoft.azure#synapseml_2.12;0.9.4: not found]

### ISSUE THREAD

**Issue by lchernicharo** [microsoft/SynapseML#1265]
When I run `spark-shell --packages com.microsoft.azure:synapseml_2.12:0.9.4`, as described in the [SynapseML Website](https://microsoft.github.io/SynapseML/), the shell cannot start, returning the stacktrace below. If I start spark-shell without this package option it starts with no problem.

**To Reproduce**
- Open new terminal window
- run `start-master.sh` to start Spark standalone
- run `spark-shell --packages com.microsoft.azure:synapseml_2.12:0.9.4`

**Expected behavior**
Run `spark-shell`correctly with SynapseML 0.94 installed.

**Info:**
 - SynapseML Version: v0.94
 - Spark Version 3.1.2
 - Spark Platform: Local Standalone
 - Java version: OpenJDK 11

** Stacktrace**
```
Exception in thread "main" java.lang.RuntimeException: [unresolved dependency: com.microsoft.azure#synapseml_2.12;0.9.4: not found]
	at org.apache.spark.deploy.SparkSubmitUtils$.resolveMavenCoordinates(SparkSubmit.scala:1429)
	at org.apache.spark.deploy.DependencyUtils$.resolveMavenDependencies(DependencyUtils.scala:54)
	at org.apache.spark.deploy.SparkSubmit.prepareSubmitEnvironment(SparkSubmit.scala:308)
	at org.apache.spark.deploy.SparkSubmit.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:894)
	at org.apache.spark.deploy.SparkSubmit.doRunMain$1(SparkSubmit.scala:180)
	at org.apache.spark.deploy.SparkSubmit.submit(SparkSubmit.scala:203)
	at org.apache.spark.deploy.SparkSubmit.doSubmit(SparkSubmit.scala:90)
	at org.apache.spark.deploy.SparkSubmit$$anon$2.doSubmit(SparkSubmit.scala:1039)
	at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:1048)
	at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)

```

**Comment by lchernicharo** [comment]
I was able to install it using `spark-shell --packages com.microsoft.azure:synapseml_2.12:0.9.4 --conf spark.jars.repositories=https://mmlspark.azureedge.net/maven` but still think it's an issue to be solved. One should be able to install without the --conf tag or Microsoft should fix the instructions in the web site.

**Comment by mhamilton723** [comment]
Thanks for the fix @lchernicharo we will update!
