### ISSUE TITLE
Unable to install in Databricks

### ISSUE THREAD

**Issue by stephlocke** [microsoft/SynapseML#1287]
**Describe the bug**
Following up from #1257 which said the v0.94 should work, I am getting resolution errors when trying to install this package in databricks.

**To Reproduce**
1. Create a new databricks resource
2. Create a databricks cluster (I used 9.1LTS)
3. Install the package from maven
coordinates  com.microsoft.azure:synapseml_2.12:0.9.4 
resolver: https://mmlspark.azureedge.net/maven

**Expected behavior**
Install succeeded

**Info**
 - SynapseML Version: com.microsoft.azure:synapseml_2.12:0.9.4 
 - Databricks: 9.1 LTS (includes Apache Spark 3.1.2, Scala 2.12)

**Stacktrace**

```
Library resolution failed. Cause: java.lang.RuntimeException: unresolved dependency: com.microsoft.ml.spark:synapseml_2.12:0.9.4: not found
	at com.databricks.libraries.server.MavenInstaller.doDownloadMavenPackages(MavenLibraryResolver.scala:437)
	at com.databricks.libraries.server.MavenInstaller.$anonfun$downloadMavenPackages$2(MavenLibraryResolver.scala:381)
	at com.databricks.backend.common.util.FileUtils$.withTemporaryDirectory(FileUtils.scala:466)
	at com.databricks.libraries.server.MavenInstaller.$anonfun$downloadMavenPackages$1(MavenLibraryResolver.scala:380)
	at com.databricks.logging.UsageLogging.$anonfun$recordOperation$1(UsageLogging.scala:341)
	at com.databricks.logging.UsageLogging.executeThunkAndCaptureResultTags$1(UsageLogging.scala:435)
	at com.databricks.logging.UsageLogging.$anonfun$recordOperationWithResultTags$4(UsageLogging.scala:455)
	at com.databricks.logging.UsageLogging.$anonfun$withAttributionContext$1(UsageLogging.scala:215)
	at scala.util.DynamicVariable.withValue(DynamicVariable.scala:62)
	at com.databricks.logging.AttributionContext$.withValue(AttributionContext.scala:95)
	at com.databricks.logging.UsageLogging.withAttributionContext(UsageLogging.scala:213)
	at com.databricks.logging.UsageLogging.withAttributionContext$(UsageLogging.scala:210)
	at com.databricks.libraries.server.MavenInstaller.withAttributionContext(MavenLibraryResolver.scala:57)
	at com.databricks.logging.UsageLogging.withAttributionTags(UsageLogging.scala:251)
	at com.databricks.logging.UsageLogging.withAttributionTags$(UsageLogging.scala:243)
	at com.databricks.libraries.server.MavenInstaller.withAttributionTags(MavenLibraryResolver.scala:57)
	at com.databricks.logging.UsageLogging.recordOperationWithResultTags(UsageLogging.scala:430)
	at com.databricks.logging.UsageLogging.recordOperationWithResultTags$(UsageLogging.scala:350)
	at com.databricks.libraries.server.MavenInstaller.recordOperationWithResultTags(MavenLibraryResolver.scala:57)
	at com.databricks.logging.UsageLogging.recordOperation(UsageLogging.scala:341)
	at com.databricks.logging.UsageLogging.recordOperation$(UsageLogging.scala:313)
	at com.databricks.libraries.server.MavenInstaller.recordOperation(MavenLibraryResolver.scala:57)
	at com.databricks.libraries.server.MavenInstaller.downloadMavenPackages(MavenLibraryResolver.scala:379)
	at com.databricks.libraries.server.MavenInstaller.downloadMavenPackagesWithRetry(MavenLibraryResolver.scala:137)
	at com.databricks.libraries.server.MavenInstaller.resolveMavenPackages(MavenLibraryResolver.scala:113)
	at com.databricks.libraries.server.MavenLibraryResolver.resolve(MavenLibraryResolver.scala:44)
	at com.databricks.libraries.server.ManagedLibraryManager$GenericManagedLibraryResolver.resolve(ManagedLibraryManager.scala:243)
	at com.databricks.libraries.server.ManagedLibraryManagerImpl$.$anonfun$resolvePrimitives$1(ManagedLibraryManagerImpl.scala:1222)
	at com.databricks.libraries.server.ManagedLibraryManagerImpl$.$anonfun$resolvePrimitives$1$adapted(ManagedLibraryManagerImpl.scala:1217)
	at scala.collection.Iterator.foreach(Iterator.scala:943)
	at scala.collection.Iterator.foreach$(Iterator.scala:943)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1431)
	at scala.collection.IterableLike.foreach(IterableLike.scala:74)
	at scala.collection.IterableLike.foreach$(IterableLike.scala:73)
	at scala.collection.AbstractIterable.foreach(Iterable.scala:56)
	at com.databricks.libraries.server.ManagedLibraryManagerImpl$.resolvePrimitives(ManagedLibraryManagerImpl.scala:1217)
	at com.databricks.libraries.server.ManagedLibraryManagerImpl$ClusterStatus.installLibsWithResolution(ManagedLibraryManagerImpl.scala:719)
	at com.databricks.libraries.server.ManagedLibraryManagerImpl$ClusterStatus.installLibs(ManagedLibraryManagerImpl.scala:705)
	at com.databricks.libraries.server.ManagedLibraryManagerImpl$InstallLibTask$1.run(ManagedLibraryManagerImpl.scala:387)
	at com.databricks.threading.NamedExecutor$$anon$2.$anonfun$run$1(NamedExecutor.scala:356)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
	at com.databricks.logging.UsageLogging.$anonfun$withAttributionContext$1(UsageLogging.scala:215)
	at scala.util.DynamicVariable.withValue(DynamicVariable.scala:62)
	at com.databricks.logging.AttributionContext$.withValue(AttributionContext.scala:95)
	at com.databricks.logging.UsageLogging.withAttributionContext(UsageLogging.scala:213)
	at com.databricks.logging.UsageLogging.withAttributionContext$(UsageLogging.scala:210)
	at com.databricks.threading.NamedExecutor.withAttributionContext(NamedExecutor.scala:285)
	at com.databricks.threading.NamedExecutor$$anon$2.run(NamedExecutor.scala:355)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)

```

Code owner tags: @mhamilton723 @drdarshan

**Comment by mhamilton723** [comment]
I am spinning up a cluster now to try to repro. Our build tests on 8.3 so perhaps this could be a workaround if you cannot get 9.1 to work

**Comment by mhamilton723** [comment]
I am not able to reproduce this issue on my side with 9.1LTS and 0.9.4

<img width="505" alt="image" src="https://user-images.githubusercontent.com/6456637/145352605-d10ffd1b-4c94-489d-9456-7086c9a8279d.png">

**Comment by stephlocke** [comment]
uksouth I was going for. I'll take another look and see if I can get things running now. It'd be nice if time did fix it 😂

**Comment by stephlocke** [comment]
It took about 3 clusters on each of a eastus and uksouth newly made databricks cluster to get the package to actually install and not just get a resolution issue. Since all the installs are happening in Azure, perhaps there's problems with the maven repo hosting?

**Comment by mhamilton723** [comment]
@stephlocke thanks for folloowing up. That is indeed odd as its hosted in a storage blob that doesn't seem to be acting up. In our next release we will host on maven central so perhaps that will make it more reliable for you. Also one other idea is to try the blob directly instead of the CDN
`https://mmlspark.blob.core.windows.net/maven/`

**Comment by mhamilton723** [comment]
Feel free to re-open if needed
