### ISSUE TITLE
Unable to convert to pandas or show TabularLIME results.

### ISSUE THREAD

**Issue by reyasadhu** [microsoft/SynapseML#1290]
I am using tabularLIME in the following manner.
'''
lime=TabularLIME(
                 inputCols=categorical_features+numeric_features,
                 categoricalFeatures=categorical_features,
                 model=fit_model,
                 outputCol='weights',
                 targetCol='probability',
                 targetClasses=[1],
                 backgroundData=broadcast(new_data.orderBy(rand()).limit(100).cache()),
                )
        
explain_instances =fit_model.transform(new_data).orderBy(rand()).limit(1).repartition(200).cache()
    
            
vec_access = udf(lambda v, i: float(v[i]), FloatType())
vec2array = udf(lambda vec: vec.toArray().tolist(), ArrayType(FloatType()))
        
lime_results =lime.transform(explain_instances)\
              .select(["weights", "probability", "label"] + categorical_features + numeric_features)\
              .withColumn("probability", vec_access("probability", lit(1)))\
              .withColumn("weights", vec2array(col("weights").getItem(0)))
'''
The lime_results dataframe is being generated, but I cannot convert it to a pandas dataframe for plotting.
'''
 ERROR Utils: Uncaught exception in thread stdout writer for python3

java.lang.NoSuchMethodError: 'breeze.generic.UFunc$UImpl breeze.linalg.sum$.vectorizeCols_Double(scala.reflect.ClassTag, breeze.storage.Zero, breeze.linalg.VectorizedReduceUFunc$VectorizeHelper)'

                    at com.microsoft.azure.synapse.ml.explainers.RegressionBase.fit(RegressionBase.scala:46)

                    at com.microsoft.azure.synapse.ml.explainers.LIMEBase.$anonfun$transform$7(LIMEBase.scala:105)

                    at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:286)

                    at scala.collection.Iterator.foreach(Iterator.scala:943)

                    at scala.collection.Iterator.foreach$(Iterator.scala:943)

                    at scala.collection.AbstractIterator.foreach(Iterator.scala:1431)

                    at scala.collection.IterableLike.foreach(IterableLike.scala:74)

                    at scala.collection.IterableLike.foreach$(IterableLike.scala:73)

                    at breeze.linalg.BroadcastedColumns$BroadcastedDMColsISeq.foreach(BroadcastedColumns.scala:163)

                    at scala.collection.TraversableLike.map(TraversableLike.scala:286)

                    at scala.collection.TraversableLike.map$(TraversableLike.scala:279)

                    at breeze.linalg.BroadcastedColumns$BroadcastedDMColsISeq.map(BroadcastedColumns.scala:163)

                    at com.microsoft.azure.synapse.ml.explainers.LIMEBase.$anonfun$transform$5(LIMEBase.scala:104)

                    at com.microsoft.azure.synapse.ml.explainers.LIMEBase.$anonfun$transform$5$adapted(LIMEBase.scala:93)

                    at org.apache.spark.sql.KeyValueGroupedDataset.$anonfun$mapGroups$1(KeyValueGroupedDataset.scala:193)

                    at org.apache.spark.sql.execution.MapGroupsExec.$anonfun$doExecute$17(objects.scala:424)

                    at scala.collection.Iterator$$anon$11.nextCur(Iterator.scala:486)

                    at scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:492)

                    at org.apache.spark.sql.catalyst.expressions.GeneratedClass$GeneratedIteratorForCodegenStage4.processNext(Unknown Source)

                    at org.apache.spark.sql.execution.BufferedRowIterator.hasNext(BufferedRowIterator.java:43)

                    at org.apache.spark.sql.execution.WholeStageCodegenExec$$anon$1.hasNext(WholeStageCodegenExec.scala:759)

                    at scala.collection.Iterator$$anon$10.hasNext(Iterator.scala:460)

                    at org.apache.spark.ContextAwareIterator.hasNext(ContextAwareIterator.scala:39)

                    at scala.collection.Iterator$$anon$10.hasNext(Iterator.scala:460)

                    at scala.collection.Iterator$$anon$10.hasNext(Iterator.scala:460)

                    at scala.collection.Iterator$GroupedIterator.fill(Iterator.scala:1211)

                    at scala.collection.Iterator$GroupedIterator.hasNext(Iterator.scala:1217)

                    at scala.collection.Iterator$$anon$10.hasNext(Iterator.scala:460)

                    at scala.collection.Iterator.foreach(Iterator.scala:943)

                    at scala.collection.Iterator.foreach$(Iterator.scala:943)

                    at scala.collection.AbstractIterator.foreach(Iterator.scala:1431)

                    at org.apache.spark.api.python.PythonRDD$.writeIteratorToStream(PythonRDD.scala:307)

                    at org.apache.spark.sql.execution.python.PythonUDFRunner$$anon$1.writeIteratorToStream(PythonUDFRunner.scala:53)

                    at org.apache.spark.api.python.BasePythonRunner$WriterThread.$anonfun$run$1(PythonRunner.scala:424)

                    at org.apache.spark.util.Utils$.logUncaughtExceptions(Utils.scala:2019)

                    at org.apache.spark.api.python.BasePythonRunner$WriterThread.run(PythonRunner.scala:259)

Exception in thread "stdout writer for python3" java.lang.NoSuchMethodError: 'breeze.generic.UFunc$UImpl breeze.linalg.sum$.vectorizeCols_Double(scala.reflect.ClassTag, breeze.storage.Zero, breeze.linalg.VectorizedReduceUFunc$VectorizeHelper)'

                    at com.microsoft.azure.synapse.ml.explainers.RegressionBase.fit(RegressionBase.scala:46)

                    at com.microsoft.azure.synapse.ml.explainers.LIMEBase.$anonfun$transform$7(LIMEBase.scala:105)

                    at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:286)

                    at scala.collection.Iterator.foreach(Iterator.scala:943)

                    at scala.collection.Iterator.foreach$(Iterator.scala:943)

                    at scala.collection.AbstractIterator.foreach(Iterator.scala:1431)

                    at scala.collection.IterableLike.foreach(IterableLike.scala:74)

                    at scala.collection.IterableLike.foreach$(IterableLike.scala:73)

                    at breeze.linalg.BroadcastedColumns$BroadcastedDMColsISeq.foreach(BroadcastedColumns.scala:163)

                    at scala.collection.TraversableLike.map(TraversableLike.scala:286)

                    at scala.collection.TraversableLike.map$(TraversableLike.scala:279)

                    at breeze.linalg.BroadcastedColumns$BroadcastedDMColsISeq.map(BroadcastedColumns.scala:163)

                    at com.microsoft.azure.synapse.ml.explainers.LIMEBase.$anonfun$transform$5(LIMEBase.scala:104)

                    at com.microsoft.azure.synapse.ml.explainers.LIMEBase.$anonfun$transform$5$adapted(LIMEBase.scala:93)

                    at org.apache.spark.sql.KeyValueGroupedDataset.$anonfun$mapGroups$1(KeyValueGroupedDataset.scala:193)

                    at org.apache.spark.sql.execution.MapGroupsExec.$anonfun$doExecute$17(objects.scala:424)

                    at scala.collection.Iterator$$anon$11.nextCur(Iterator.scala:486)

                    at scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:492)

                    at org.apache.spark.sql.catalyst.expressions.GeneratedClass$GeneratedIteratorForCodegenStage4.processNext(Unknown Source)

                    at org.apache.spark.sql.execution.BufferedRowIterator.hasNext(BufferedRowIterator.java:43)

                    at org.apache.spark.sql.execution.WholeStageCodegenExec$$anon$1.hasNext(WholeStageCodegenExec.scala:759)

                    at scala.collection.Iterator$$anon$10.hasNext(Iterator.scala:460)

                    at org.apache.spark.ContextAwareIterator.hasNext(ContextAwareIterator.scala:39)

                    at scala.collection.Iterator$$anon$10.hasNext(Iterator.scala:460)

                    at scala.collection.Iterator$$anon$10.hasNext(Iterator.scala:460)

                    at scala.collection.Iterator$GroupedIterator.fill(Iterator.scala:1211)

                    at scala.collection.Iterator$GroupedIterator.hasNext(Iterator.scala:1217)

                    at scala.collection.Iterator$$anon$10.hasNext(Iterator.scala:460)

                    at scala.collection.Iterator.foreach(Iterator.scala:943)

                    at scala.collection.Iterator.foreach$(Iterator.scala:943)

                    at scala.collection.AbstractIterator.foreach(Iterator.scala:1431)

                    at org.apache.spark.api.python.PythonRDD$.writeIteratorToStream(PythonRDD.scala:307)

                    at org.apache.spark.sql.execution.python.PythonUDFRunner$$anon$1.writeIteratorToStream(PythonUDFRunner.scala:53)

                    at org.apache.spark.api.python.BasePythonRunner$WriterThread.$anonfun$run$1(PythonRunner.scala:424)

                    at org.apache.spark.util.Utils$.logUncaughtExceptions(Utils.scala:2019)

                    at org.apache.spark.api.python.BasePythonRunner$WriterThread.run(PythonRunner.scala:259)

[Stage 148:>                                                        (0 + 1) / 1]
'''

The versions I am using:
 - SynapseML Version: 0.9.4
 - Spark Version: 3.2.0
 - Python version: 3.7.10
 - Spark Platform: Kaggle

The sparkContext is created like this,
spark = pyspark.sql.SparkSession.builder.appName("MyApp") \
            .config("spark.jars.packages", "com.microsoft.azure:synapseml_2.12:0.9.4") \
            .config("spark.jars.repositories", "https://mmlspark.azureedge.net/maven") \
            .getOrCreate()

**Comment by mhamilton723** [comment]
Thank you for raising this, tagging in @memoryz who has built this stack!

**Comment by memoryz** [comment]
Ack. Looking into this.

**Comment by memoryz** [comment]
@reyasadhu The issue is caused by difference in breeze version between Spark 3.1.2 and Spark 3.2.0. SynapseML 0.9.4 was built with Spark 3.1.2, and the functionality involved here currently doesn't work with Spark 3.2.0. While we investigate a permanent fix, can you lower your Spark version to 3.1.2?

**Comment by memoryz** [comment]
This issue can be reproduced on [Databricks Runtime 10.2](https://docs.microsoft.com/en-us/azure/databricks/release-notes/runtime/10.2).

Although Databricks 10.0 and 10.1 runs on Spark 3.2.0, the breeze library is still 1.0 (reference: [Databricks Runtime 10.0](https://docs.microsoft.com/en-us/azure/databricks/release-notes/runtime/10.0), [Databricks Runtime 10.1](https://docs.microsoft.com/en-us/azure/databricks/release-notes/runtime/10.1)), so this issue doesn't reproduce on these two versions.

The fix #1299 was tested on Databricks 10.1 and 10.2.
