### ISSUE TITLE
Network init call failed in LightGBM with error: Binding port 12401 failed

### ISSUE THREAD

**Issue by liuyonglang** [microsoft/SynapseML#1311]
SynapseMl:0.9.2
spark:3.1.2

I use SynapseMl with spark 3.1.2 on yarn..

the dataset is like this:

0120030913371513,1987,40,694,1,2,10,6,32,0.12,0.6,2,2,1,1,5,450,53,659,4,0.6,0.7,0.93,0.8,4,1447.9461,60,60,2,1,7,2,2,2,4,0,0,0
0120071213327101,1995,42,756,3,3,19,4,98,0.12,0.25,0,0,1,1,1,472,25.21,774,9,0,0.1818,0.2933,4,2,4471.9414,186,186,1,5,5,0,0,0,1,0,0,0
0119110916580623,1992,50,628,3,1,29,4,179,0.12,0.45,5,5,3,4,3,465,53,695,1,0,0.0357,0,1,3,7368.2625,307,307,5,2,2,0,0,0,2,0,0,0
0120121216295730,1995,44,601,1,1,5,4,22,0.12,0.25,4,3,1,1,5,421,6.8,628,13,0,0,0.4864,0,4,93.1522,4,60,1,1,1,1,1,1,1,0,0,0
0120041909577011,1993,63,760,2,3,10,9,35,0.12,0.3,4,4,1,1,5,508,53,625,9,0.6,0.7,0.93,0.8,3,0.1853,0,60,0,0,0,0,0,0,2,0,0,1
0120083015115525,1990,38,664,2,2,23,6,108,0.12,0.3,3,3,1,1,4,457,53,741,3,0,0.18,0,4,3,0.0664,0,60,0,0,0,0,0,0,1,0,0,0
0120100614217534,1987,34,537,2,3,9,2,32,0.12,0.25,0,0,1,1,1,509,29,678,7,0,0.5,0.2497,3,4,0.2469,0,60,1,1,1,1,1,1,3,0,0,0
0120121518252660,1994,38,608,3,1,7,7,30,0.12,0.25,5,5,1,1,4,421,36.24,610,2,1,0.5294118,0.05,1,3,1.3764,0,60,0,0,0,0,0,0,3,0,0,1
0120112516300723,1981,36,587,1,2,17,4,106,0.12,0.3,1,2,1,1,5,438,39.33,630,14,0,0.3333,0.5374,2,4,36.2106,2,0,2,2,2,1,1,1,4,1,1,0
0120100210396216,1996,42,640,1,3,7,6,23,0.12,0.3,0,0,0,0,0,433,16,656,3,0,0.3333333,0.4261,1,4,270.5172,11,60,2,2,2,2,2,2,3,0,0,0
0120120421442531,1985,32,705,2,1,5,0,28,0.12,0.2,6,5,2,4,3,446,24.76,688,7,0,0,0.8762,4,3,42.4244,2,60,1,10,10,1,1,1,4,0,0,0
0120120816144362,1995,63,602,3,3,13,1,72,0.12,0.2,1,2,1,1,5,464,16.28,728,9,1,0.2727,0.4864,4,3,625.3744,26,60,0,2,2,0,0,0,1,0,0,0
0120101813246171,1993,42,672,1,3,20,3,81,0.12,0.45,1,1,1,2,3,485,18,684,4,0,0.3333,0.493,3,3,0.1217,0,60,0,0,0,0,0,0,1,0,0,0
0120091503264126,1989,32,731,2,3,18,0,88,0.12,0.3,6,5,1,3,2,384,53,659,11,0,0.4286,0.5874,6,4,0.2125,0,0,2,4,4,0,0,0,5,2,2,0
0120092713092637,1986,36,750,2,4,22,8,111,0.12,0.25,6,5,1,1,3,467,40,723,16,1,0.087,0.05,0,2,0.205,0,60,1,1,1,1,1,1,2,0,0,0
0120112320477035,1986,63,665,1,2,21,2,98,0.12,0.45,3,3,1,1,4,465,18.18,709,14,1,0.1481,0.2497,4,2,0.0636,0,60,1,0,0,1,1,1,3,0,0,0
0120101611332134,1988,33,650,2,2,9,3,20,0.12,0.6,0,0,1,1,1,459,16,683,5,0,0,0.6032,7,3,701.345,29,28,5,4,4,3,3,3,1,2,2,0
0118070411424543,1972,43,621,3,1,6,3,47,0.12,0.45,4,4,1,4,3,433,53,648,5,0.6,0.7,0.93,0.8,3,18297.5517,775,60,1,2,2,1,1,1,5,0,0,0
0120112414092176,1978,33,729,2,3,15,0,44,0.12,0.3,0,0,1,1,1,488,31.82,733,4,0,0.3333,0.4746,1,2,47.2689,2,60,2,8,8,2,2,2,5,0,0,0
0121011011451513,1995,39,709,1,3,1,4,10,0.12,0.15,6,5,4,3,3,485,5.26,679,4,0,0,0.6705,3,3,78.5314,3,60,0,2,2,0,0,0,2,0,0,0
0120090413305433,1978,36,552,4,1,5,2,57,0.12,0.3,5,4,4,5,3,509,53,671,1,0,0,0.3761,2,3,0.0964,0,60,0,1,1,0,0,0,1,0,0,0
0120111722324070,1993,40,688,0,1,8,1,22,0.12,0.2,2,1,1,1,5,433,37.93,593,3,0,0,0.4864,0,4,9.7317,1,0,4,5,5,1,1,1,4,3,3,0
0121011012214613,1994,42,704,3,3,18,3,120,0.12,0.2,4,4,2,4,2,476,40.22,658,9,2,0.1111,0.5364,4,2,0.3014,0,60,0,5,5,0,0,0,1,0,0,1
0120092217232437,1993,88,485,2,3,28,0,111,0.12,0.45,0,0,0,0,0,364,53,585,3,0,0.4237,1,1,3,111.2647,5,0,9,2,2,1,1,1,4,7,7,1
0121010713081400,1976,48,600,2,1,3,2,11,0.12,0.2,0,0,0,0,0,433,36.84,651,2,0.6,0.7,0.93,0,4,0.1231,0,60,1,2,2,1,1,1,2,0,0,1
0120071503253512,1994,42,505,1,2,6,1,16,0.12,0.45,3,3,1,1,5,433,53,652,7,0,0.25,0.93,0.8,3,183.2806,7,7,1,6,6,0,0,0,1,1,1,0

45369 rows, 38 columns..

the spark params is :  spark.driver.memory=4G, spark.driver.cores=1, spark.executor.memory=3G, spark.executor.cores=1, spark.executor.instances=2, spark.network.timeout=600s。

LightGBM params is :              
lgb = LightGBMClassifier(featuresCol='input_feature',
                                     boostingType='goss',
                                     labelCol=‘y’,
                                     categoricalSlotIndexes=slotindex,
                                     learningRate=0.1,
                                     maxDepth=4,
                                     numIterations=10,
                                     useBarrierExecutionMode=True,
                                     numLeaves=31,
                                     maxBin=256,
                                     objective='binary'
                                     )

**When I use this lgb fit(). I got a strange problem . Sometimes I can fit successfully , But errors occur occasionally. like this:** 

: org.apache.spark.SparkException: Job aborted due to stage failure: Could not recover from a failed barrier ResultStage. Most recent failure reason: Stage failed because barrier task ResultTask(20, 0) finished unsuccessfully.
java.lang.Exception: Network init call failed in LightGBM with error: Binding port 12401 failed
	at com.microsoft.azure.synapse.ml.lightgbm.LightGBMUtils$.validate(LightGBMUtils.scala:24)
	at com.microsoft.azure.synapse.ml.lightgbm.TrainUtils$.networkInit(TrainUtils.scala:283)
	at com.microsoft.azure.synapse.ml.lightgbm.TrainUtils$.networkInit(TrainUtils.scala:290)
	at com.microsoft.azure.synapse.ml.lightgbm.TrainUtils$.networkInit(TrainUtils.scala:290)
	at com.microsoft.azure.synapse.ml.lightgbm.TrainUtils$.networkInit(TrainUtils.scala:290)
	at com.microsoft.azure.synapse.ml.lightgbm.LightGBMBase.trainLightGBM(LightGBMBase.scala:371)
	at com.microsoft.azure.synapse.ml.lightgbm.LightGBMBase.$anonfun$innerTrain$4(LightGBMBase.scala:480)
	at org.apache.spark.rdd.RDDBarrier.$anonfun$mapPartitions$2(RDDBarrier.scala:51)
	at org.apache.spark.rdd.RDDBarrier.$anonfun$mapPartitions$2$adapted(RDDBarrier.scala:51)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:52)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:373)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:337)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:90)
	at org.apache.spark.scheduler.Task.run(Task.scala:131)
	at org.apache.spark.executor.Executor$TaskRunner.$anonfun$run$3(Executor.scala:497)
	at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1439)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:500)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
	at org.apache.spark.scheduler.DAGScheduler.failJobAndIndependentStages(DAGScheduler.scala:2258)
	at org.apache.spark.scheduler.DAGScheduler.$anonfun$abortStage$2(DAGScheduler.scala:2207)
	at org.apache.spark.scheduler.DAGScheduler.$anonfun$abortStage$2$adapted(DAGScheduler.scala:2206)
	at scala.collection.mutable.ResizableArray.foreach(ResizableArray.scala:62)
	at scala.collection.mutable.ResizableArray.foreach$(ResizableArray.scala:55)
	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:49)
	at org.apache.spark.scheduler.DAGScheduler.abortStage(DAGScheduler.scala:2206)
	at org.apache.spark.scheduler.DAGScheduler.handleTaskCompletion(DAGScheduler.scala:1968)
	at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.doOnReceive(DAGScheduler.scala:2442)
	at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.onReceive(DAGScheduler.scala:2387)
	at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.onReceive(DAGScheduler.scala:2376)
	at org.apache.spark.util.EventLoop$$anon$1.run(EventLoop.scala:49)
	at org.apache.spark.scheduler.DAGScheduler.runJob(DAGScheduler.scala:868)
	at org.apache.spark.SparkContext.runJob(SparkContext.scala:2196)
	at org.apache.spark.SparkContext.runJob(SparkContext.scala:2291)
	at org.apache.spark.rdd.RDD.$anonfun$reduce$1(RDD.scala:1120)
	at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:151)
	at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:112)
	at org.apache.spark.rdd.RDD.withScope(RDD.scala:414)
	at org.apache.spark.rdd.RDD.reduce(RDD.scala:1102)
	at com.microsoft.azure.synapse.ml.lightgbm.LightGBMBase.innerTrain(LightGBMBase.scala:483)
	at com.microsoft.azure.synapse.ml.lightgbm.LightGBMBase.innerTrain$(LightGBMBase.scala:442)
	at com.microsoft.azure.synapse.ml.lightgbm.LightGBMClassifier.innerTrain(LightGBMClassifier.scala:26)
	at com.microsoft.azure.synapse.ml.lightgbm.LightGBMBase.$anonfun$train$1(LightGBMBase.scala:63)
	at com.microsoft.azure.synapse.ml.logging.BasicLogging.logVerb(BasicLogging.scala:63)
	at com.microsoft.azure.synapse.ml.logging.BasicLogging.logVerb$(BasicLogging.scala:60)
	at com.microsoft.azure.synapse.ml.lightgbm.LightGBMClassifier.logVerb(LightGBMClassifier.scala:26)
	at com.microsoft.azure.synapse.ml.logging.BasicLogging.logTrain(BasicLogging.scala:49)
	at com.microsoft.azure.synapse.ml.logging.BasicLogging.logTrain$(BasicLogging.scala:48)
	at com.microsoft.azure.synapse.ml.lightgbm.LightGBMClassifier.logTrain(LightGBMClassifier.scala:26)
	at com.microsoft.azure.synapse.ml.lightgbm.LightGBMBase.train(LightGBMBase.scala:44)
	at com.microsoft.azure.synapse.ml.lightgbm.LightGBMBase.train$(LightGBMBase.scala:43)
	at com.microsoft.azure.synapse.ml.lightgbm.LightGBMClassifier.train(LightGBMClassifier.scala:26)
	at com.microsoft.azure.synapse.ml.lightgbm.LightGBMClassifier.train(LightGBMClassifier.scala:26)
	at org.apache.spark.ml.Predictor.fit(Predictor.scala:151)
	at org.apache.spark.ml.Predictor.fit(Predictor.scala:115)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
	at py4j.Gateway.invoke(Gateway.java:282)
	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
	at py4j.commands.CallCommand.execute(CallCommand.java:79)
	at py4j.GatewayConnection.run(GatewayConnection.java:238)
	at java.lang.Thread.run(Thread.java:748)

 The yarn log is :
1/12/16 18:32:47 INFO lightgbm.LightGBMClassifier: driver received socket from task: 172.16.162.23:12401
21/12/16 18:32:47 INFO lightgbm.LightGBMClassifier: driver accepting a new connection...
21/12/16 18:32:47 INFO spark.BarrierCoordinator: Current barrier epoch for Stage 23 (Attempt 0) is 0.
21/12/16 18:32:47 INFO spark.BarrierCoordinator: Barrier sync epoch 0 from Stage 23 (Attempt 0) received update from Task 358, current progress: 1/2.
21/12/16 18:32:47 INFO lightgbm.LightGBMClassifier: driver received socket from task: 172.16.162.23:12403
21/12/16 18:32:47 INFO lightgbm.LightGBMClassifier: driver accepting a new connection...
21/12/16 18:32:47 INFO spark.BarrierCoordinator: Current barrier epoch for Stage 23 (Attempt 0) is 0.
21/12/16 18:32:47 INFO spark.BarrierCoordinator: Barrier sync epoch 0 from Stage 23 (Attempt 0) received update from Task 359, current progress: 2/2.
21/12/16 18:32:47 INFO spark.BarrierCoordinator: Barrier sync epoch 0 from Stage 23 (Attempt 0) received all updates from tasks, finished successfully.
21/12/16 18:32:48 INFO cluster.YarnClusterScheduler: Skip current round of resource offers for barrier stage 23 because the barrier taskSet requires 2 slots, while the total number of available slots is 0.
21/12/16 18:32:48 INFO lightgbm.LightGBMClassifier: driver received all tasks from barrier stage
21/12/16 18:32:48 INFO lightgbm.LightGBMClassifier: driver writing back to all connections: 172.16.162.23:12401,172.16.162.23:12403
21/12/16 18:32:48 INFO lightgbm.LightGBMClassifier: driver closing all sockets and server socket
21/12/16 18:32:49 INFO cluster.YarnClusterScheduler: Skip current round of resource offers for barrier stage 23 because the barrier taskSet requires 2 slots, while the total number of available slots is 0.
21/12/16 18:32:50 INFO cluster.YarnClusterScheduler: Skip current round of resource offers for barrier stage 23 because the barrier taskSet requires 2 slots, while the total number of available slots is 0.
21/12/16 18:32:51 INFO cluster.YarnClusterScheduler: Skip current round of resource offers for barrier stage 23 because the barrier taskSet requires 2 slots, while the total number of available slots is 0.
21/12/16 18:32:52 INFO cluster.YarnClusterScheduler: Skip current round of resource offers for barrier stage 23 because the barrier taskSet requires 2 slots, while the total number of available slots is 0.
21/12/16 18:32:53 INFO cluster.YarnClusterScheduler: Skip current round of resource offers for barrier stage 23 because the barrier taskSet requires 2 slots, while the total number of available slots is 0.
21/12/16 18:32:54 INFO cluster.YarnClusterScheduler: Skip current round of resource offers for barrier stage 23 because the barrier taskSet requires 2 slots, while the total number of available slots is 0.
21/12/16 18:32:55 INFO cluster.YarnClusterScheduler: Skip current round of resource offers for barrier stage 23 because the barrier taskSet requires 2 slots, while the total number of available slots is 0.
21/12/16 18:32:56 INFO cluster.YarnClusterScheduler: Skip current round of resource offers for barrier stage 23 because the barrier taskSet requires 2 slots, while the total number of available slots is 0.
21/12/16 18:32:57 INFO cluster.YarnClusterScheduler: Skip current round of resource offers for barrier stage 23 because the barrier taskSet requires 2 slots, while the total number of available slots is 0.
21/12/16 18:32:58 INFO cluster.YarnClusterScheduler: Skip current round of resource offers for barrier stage 23 because the barrier taskSet requires 2 slots, while the total number of available slots is 0.
21/12/16 18:32:59 INFO cluster.YarnClusterScheduler: Skip current round of resource offers for barrier stage 23 because the barrier taskSet requires 2 slots, while the total number of available slots is 0.
21/12/16 18:33:00 INFO cluster.YarnClusterScheduler: Skip current round of resource offers for barrier stage 23 because the barrier taskSet requires 2 slots, while the total number of available slots is 0.
21/12/16 18:33:01 INFO cluster.YarnClusterScheduler: Skip current round of resource offers for barrier stage 23 because the barrier taskSet requires 2 slots, while the total number of available slots is 0.
21/12/16 18:33:02 INFO cluster.YarnClusterScheduler: Skip current round of resource offers for barrier stage 23 because the barrier taskSet requires 2 slots, while the total number of available slots is 0.
21/12/16 18:33:03 INFO cluster.YarnClusterScheduler: Skip current round of resource offers for barrier stage 23 because the barrier taskSet requires 2 slots, while the total number of available slots is 0.
21/12/16 18:33:04 INFO cluster.YarnClusterScheduler: Skip current round of resource offers for barrier stage 23 because the barrier taskSet requires 2 slots, while the total number of available slots is 1.
21/12/16 18:33:04 WARN scheduler.TaskSetManager: Lost task 1.0 in stage 23.0 (TID 359) (bdp-hadoop-1 executor 2): java.lang.Exception: Network init call failed in LightGBM with error: Binding port 12403 failed
	at com.microsoft.azure.synapse.ml.lightgbm.LightGBMUtils$.validate(LightGBMUtils.scala:24)
	at com.microsoft.azure.synapse.ml.lightgbm.TrainUtils$.networkInit(TrainUtils.scala:283)
	at com.microsoft.azure.synapse.ml.lightgbm.TrainUtils$.networkInit(TrainUtils.scala:290)
	at com.microsoft.azure.synapse.ml.lightgbm.TrainUtils$.networkInit(TrainUtils.scala:290)
	at com.microsoft.azure.synapse.ml.lightgbm.TrainUtils$.networkInit(TrainUtils.scala:290)
	at com.microsoft.azure.synapse.ml.lightgbm.LightGBMBase.trainLightGBM(LightGBMBase.scala:371)
	at com.microsoft.azure.synapse.ml.lightgbm.LightGBMBase.$anonfun$innerTrain$4(LightGBMBase.scala:480)
	at org.apache.spark.rdd.RDDBarrier.$anonfun$mapPartitions$2(RDDBarrier.scala:51)
	at org.apache.spark.rdd.RDDBarrier.$anonfun$mapPartitions$2$adapted(RDDBarrier.scala:51)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:52)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:373)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:337)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:90)
	at org.apache.spark.scheduler.Task.run(Task.scala:131)
	at org.apache.spark.executor.Executor$TaskRunner.$anonfun$run$3(Executor.scala:497)
	at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1439)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:500)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

When got some ' required slots not equal available slots ' , Then this trainning will fail. Could you please give me some ideas about this problem. Thanks a lot.

**Comment by zijieRen** [comment]
I have also encountered this situation.  pyspark3 and SynapseMl:0.9.2。
It worked when got data from sql , But errors occurred when got data from hdfs files

**Comment by imatiach-msft** [comment]
hi @liuyonglang it looks like here you are setting:
categoricalSlotIndexes=slotindex
and you see error:
```
required slots not equal available slots
```
this means that there is something strange about the slotindex you are specifying to the model.

**Comment by ranadeepsingh** [comment]
Thank you for reaching out. The intermittent 'required slots not equal available slots' error occurred because categoricalSlotIndexes contained indices that did not match the assembled feature vector schema across data sources. As this configuration issue was diagnosed and answered, we are closing this issue.
