### ISSUE TITLE
TextAnalyze transformer does not properly handle failed ResponseTasks from Cognitive Services

### ISSUE THREAD

**Issue by dayland** [microsoft/SynapseML#1452]
**Describe the bug**
When processing files through SynapseML using the TextAnalyse() transformer, Cognitive Services can return an error status on one or more of the Analyze Tasks. When this error status occurs, SynapseML fails to parse the the returned JSON and generates and error that fails the tasks in the Apache Spark Application. 
 
**To Reproduce**
Send a file to Azure Text Analytics Analyze enpoint that returns a failed tasks status such as:
![MicrosoftTeams-image (3)](https://user-images.githubusercontent.com/48474707/160072096-a5273083-7617-4771-832b-3317e358cd2f.png)

**Expected behavior**
SynapseML TextAnalyze transformer would log the error into the error column and still return the remaining Analyze Task results as a valid response. 

**Info (please complete the following information):**
 - SynapseML Version: 0.9.5
 - Spark Version: 3.1
 - Spark Platform: Azure Synapse Workspace

** Stacktrace**
```
ERROR Executor [Executor task launch worker for task 4.0 in stage 0.0 (TID 4)]: Exception in task 4.0 in stage 0.0 (TID 4)
org.apache.spark.SparkException: Failed to execute user defined function(functions$$$Lambda$717/268536514: (struct<status:string,errors:array<struct>,displayName:string,tasks:struct<completed:int,failed:int,inprogress:int,total:int,entityrecognitiontasks:array<struct<state:string,results:struct<documents:array<struct<id:string,entities:array<struct>,warnings:array<struct>,statistics:struct>>,errors:array<struct>,modelVersion:string>>>,entityLinkingTasks:array<struct<state:string,results:struct<documents:array<struct<id:string,entities:array<struct<name:string,matches:array<struct>,language:string,id:string,url:string,dataSource:string>>,warnings:array<struct>,statistics:struct>>,errors:array<struct>,modelVersion:string>>>,entityRecognitionPiiTasks:array<struct<state:string,results:struct<documents:array<struct<id:string,entities:array<struct>,redactedText:string,warnings:array<struct>,statistics:struct>>,errors:array<struct>,modelVersion:string>>>,keyPhraseExtractionTasks:array<struct<state:string,results:struct<documents:array<struct<id:string,keyphrases:array,warnings:array<struct>,statistics:struct>>,errors:array<struct>,modelVersion:string>>>,sentimentAnalysisTasks:array<struct<state:string,results:struct<documents:array<struct<id:string,sentiment:string,statistics:struct,confidenceScores:struct,sentences:array<struct<text:string,sentiment:string,confidencescores:struct,offset:int,length:int>>,warnings:array<struct>>>,errors:array<struct>,modelVersion:string>>>>>) => array<struct<entityrecognition:array<struct<result:struct<id:string,entities:array<struct>,warnings:array<struct>,statistics:struct>,error:struct>>,entityLinking:array<struct<result:struct<id:string,entities:array<struct<name:string,matches:array<struct>,language:string,id:string,url:string,dataSource:string>>,warnings:array<struct>,statistics:struct>,error:struct>>,entityRecognitionPii:array<struct<result:struct<id:string,entities:array<struct>,redactedText:string,warnings:array<struct>,statistics:struct>,error:struct>>,keyPhraseExtraction:array<struct<result:struct<id:string,keyphrases:array,warnings:array<struct>,statistics:struct>,error:struct>>,sentimentAnalysis:array<struct<result:struct<id:string,sentiment:string,statistics:struct,confidenceScores:struct,sentences:array<struct<text:string,sentiment:string,confidencescores:struct,offset:int,length:int>>,warnings:array<struct>>,error:struct>>>>)
        at org.apache.spark.sql.catalyst.expressions.GeneratedClass$SpecificUnsafeProjection.writeFields_8_3$(Unknown Source)
        at org.apache.spark.sql.catalyst.expressions.GeneratedClass$SpecificUnsafeProjection.apply(Unknown Source)
        at org.apache.spark.sql.catalyst.expressions.GeneratedClass$SpecificUnsafeProjection.apply(Unknown Source)
        at scala.collection.Iterator$$anon$10.next(Iterator.scala:459)
        at scala.collection.Iterator$$anon$10.next(Iterator.scala:459)
        at scala.collection.Iterator$$anon$10.next(Iterator.scala:459)
        at scala.collection.Iterator$$anon$11.nextCur(Iterator.scala:484)
        at scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:490)
        at scala.collection.Iterator$$anon$10.hasNext(Iterator.scala:458)
        at org.apache.spark.sql.catalyst.expressions.GeneratedClass$GeneratedIteratorForCodegenStage5.processNext(Unknown Source)
        at org.apache.spark.sql.execution.BufferedRowIterator.hasNext(BufferedRowIterator.java:43)
        at org.apache.spark.sql.execution.WholeStageCodegenExec$$anon$1.hasNext(WholeStageCodegenExec.scala:755)
        at scala.collection.Iterator$$anon$10.hasNext(Iterator.scala:458)
        at org.apache.spark.sql.execution.aggregate.ObjectHashAggregateExec.$anonfun$doExecute$2(ObjectHashAggregateExec.scala:87)
        at org.apache.spark.sql.execution.aggregate.ObjectHashAggregateExec.$anonfun$doExecute$2$adapted(ObjectHashAggregateExec.scala:85)
        at org.apache.spark.rdd.RDD.$anonfun$mapPartitionsWithIndexInternal$2(RDD.scala:892)
        at org.apache.spark.rdd.RDD.$anonfun$mapPartitionsWithIndexInternal$2$adapted(RDD.scala:892)
        at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:52)
        at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:374)
        at org.apache.spark.rdd.RDD.iterator(RDD.scala:338)
        at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:52)
        at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:374)
        at org.apache.spark.rdd.RDD.iterator(RDD.scala:338)
        at org.apache.spark.shuffle.ShuffleWriteProcessor.write(ShuffleWriteProcessor.scala:59)
        at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:99)
        at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:52)
        at org.apache.spark.scheduler.Task.run(Task.scala:131)
        at org.apache.spark.executor.Executor$TaskRunner.$anonfun$run$3(Executor.scala:497)
        at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1439)
        at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:500)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.IllegalArgumentException: The value (0) of the type (java.lang.Integer) cannot be converted to the string type
        at org.apache.spark.sql.catalyst.CatalystTypeConverters$StringConverter$.toCatalystImpl(CatalystTypeConverters.scala:297)
        at org.apache.spark.sql.catalyst.CatalystTypeConverters$StringConverter$.toCatalystImpl(CatalystTypeConverters.scala:289)
        at org.apache.spark.sql.catalyst.CatalystTypeConverters$CatalystTypeConverter.toCatalyst(CatalystTypeConverters.scala:107)
        at org.apache.spark.sql.catalyst.CatalystTypeConverters$StructConverter.toCatalystImpl(CatalystTypeConverters.scala:262)
        at org.apache.spark.sql.catalyst.CatalystTypeConverters$StructConverter.toCatalystImpl(CatalystTypeConverters.scala:242)
        at org.apache.spark.sql.catalyst.CatalystTypeConverters$CatalystTypeConverter.toCatalyst(CatalystTypeConverters.scala:107)
        at org.apache.spark.sql.catalyst.CatalystTypeConverters$StructConverter.toCatalystImpl(CatalystTypeConverters.scala:252)
        at org.apache.spark.sql.catalyst.CatalystTypeConverters$StructConverter.toCatalystImpl(CatalystTypeConverters.scala:242)
        at org.apache.spark.sql.catalyst.CatalystTypeConverters$CatalystTypeConverter.toCatalyst(CatalystTypeConverters.scala:107)
        at org.apache.spark.sql.catalyst.CatalystTypeConverters$ArrayConverter.$anonfun$toCatalystImpl$2(CatalystTypeConverters.scala:168)
        at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:238)
        at scala.collection.mutable.ResizableArray.foreach(ResizableArray.scala:62)
        at scala.collection.mutable.ResizableArray.foreach$(ResizableArray.scala:55)
        at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:49)
        at scala.collection.TraversableLike.map(TraversableLike.scala:238)
        at scala.collection.TraversableLike.map$(TraversableLike.scala:231)
        at scala.collection.AbstractTraversable.map(Traversable.scala:108)
        at org.apache.spark.sql.catalyst.CatalystTypeConverters$ArrayConverter.toCatalystImpl(CatalystTypeConverters.scala:168)
        at org.apache.spark.sql.catalyst.CatalystTypeConverters$ArrayConverter.toCatalystImpl(CatalystTypeConverters.scala:158)
        at org.apache.spark.sql.catalyst.CatalystTypeConverters$CatalystTypeConverter.toCatalyst(CatalystTypeConverters.scala:102)
        at org.apache.spark.sql.catalyst.CatalystTypeConverters$StructConverter.toCatalystImpl(CatalystTypeConverters.scala:252)
        at org.apache.spark.sql.catalyst.CatalystTypeConverters$StructConverter.toCatalystImpl(CatalystTypeConverters.scala:242)
        at org.apache.spark.sql.catalyst.CatalystTypeConverters$CatalystTypeConverter.toCatalyst(CatalystTypeConverters.scala:107)
        at org.apache.spark.sql.catalyst.CatalystTypeConverters$ArrayConverter.$anonfun$toCatalystImpl$2(CatalystTypeConverters.scala:168)
        at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:238)
        at scala.collection.Iterator.foreach(Iterator.scala:941)
        at scala.collection.Iterator.foreach$(Iterator.scala:941)
        at scala.collection.AbstractIterator.foreach(Iterator.scala:1429)
        at scala.collection.IterableLike.foreach(IterableLike.scala:74)
        at scala.collection.IterableLike.foreach$(IterableLike.scala:73)
        at scala.collection.AbstractIterable.foreach(Iterable.scala:56)
        at scala.collection.TraversableLike.map(TraversableLike.scala:238)
        at scala.collection.TraversableLike.map$(TraversableLike.scala:231)
        at scala.collection.AbstractTraversable.map(Traversable.scala:108)
        at org.apache.spark.sql.catalyst.CatalystTypeConverters$ArrayConverter.toCatalystImpl(CatalystTypeConverters.scala:168)
        at org.apache.spark.sql.catalyst.CatalystTypeConverters$ArrayConverter.toCatalystImpl(CatalystTypeConverters.scala:158)
        at org.apache.spark.sql.catalyst.CatalystTypeConverters$CatalystTypeConverter.toCatalyst(CatalystTypeConverters.scala:102)
        at org.apache.spark.sql.catalyst.CatalystTypeConverters$.$anonfun$createToCatalystConverter$2(CatalystTypeConverters.scala:426)
        ... 33 
```

@mhamilton723, @stuartleeks

**Comment by mhamilton723** [comment]
#1453 Fixes this :)
