### ISSUE TITLE
Fail to load saved LightGBM model

### ISSUE THREAD

**Issue by HXY777** [microsoft/SynapseML#1588]
### SynapseML version

0.10.0

### System information

- **Language version**: python 3.9.5, scala 2.1.2
- **Spark Version**: 3.3.0
- **Spark Platform**: Databricks (11.1 ML Beta)

### Describe the problem

Failed to load LightGBM on a newly started Databricks ML cluster with the error 

> java.lang.UnsatisfiedLinkError: 'long com.microsoft.ml.lightgbm.lightgbmlibJNI.voidpp_handle()'.

However, after I trained a LightGBM in the same cluster, I was able to load the saved model.

### Code to reproduce issue

```
LightGBMClassificationModel.loadNativeModelFromFile("dbfs:...)
```

### Other info / logs

```
---------------------------------------------------------------------------
Py4JJavaError                             Traceback (most recent call last)
<command-887518698409851> in <cell line: 1>()
----> 1 LightGBMClassificationModel.loadNativeModelFromFile("dbfs:/.../model")

/local_disk0/...com_microsoft_azure_synapseml_lightgbm_2_12_0_10_0-36073.jar/synapse/ml/lightgbm/LightGBMClassificationModel.py in loadNativeModelFromFile(filename)
     23             ctx._jvm.com.microsoft.azure.synapse.ml.lightgbm.LightGBMClassificationModel
     24         )
---> 25         java_model = loader.loadNativeModelFromFile(filename)
     26         return JavaParams._from_java(java_model)
     27 

/databricks/spark/python/lib/py4j-0.10.9.5-src.zip/py4j/java_gateway.py in __call__(self, *args)
   1319 
   1320         answer = self.gateway_client.send_command(command)
-> 1321         return_value = get_return_value(
   1322             answer, self.gateway_client, self.target_id, self.name)
   1323 

/databricks/spark/python/pyspark/sql/utils.py in deco(*a, **kw)
    194     def deco(*a: Any, **kw: Any) -> Any:
    195         try:
--> 196             return f(*a, **kw)
    197         except Py4JJavaError as e:
    198             converted = convert_exception(e.java_exception)

/databricks/spark/python/lib/py4j-0.10.9.5-src.zip/py4j/protocol.py in get_return_value(answer, gateway_client, target_id, name)
    324             value = OUTPUT_CONVERTER[type](answer[2:], gateway_client)
    325             if answer[1] == REFERENCE_TYPE:
--> 326                 raise Py4JJavaError(
    327                     "An error occurred while calling {0}{1}{2}.\n".
    328                     format(target_id, ".", name), value)

Py4JJavaError: An error occurred while calling z:com.microsoft.azure.synapse.ml.lightgbm.LightGBMClassificationModel.loadNativeModelFromFile.
: java.lang.UnsatisfiedLinkError: 'long com.microsoft.ml.lightgbm.lightgbmlibJNI.voidpp_handle()'
	at com.microsoft.ml.lightgbm.lightgbmlibJNI.voidpp_handle(Native Method)
	at com.microsoft.ml.lightgbm.lightgbmlib.voidpp_handle(lightgbmlib.java:628)
	at com.microsoft.azure.synapse.ml.lightgbm.booster.BoosterHandler$.com$microsoft$azure$synapse$ml$lightgbm$booster$BoosterHandler$$createBoosterPtrFromModelString(LightGBMBooster.scala:42)
	at com.microsoft.azure.synapse.ml.lightgbm.booster.BoosterHandler.<init>(LightGBMBooster.scala:64)
	at com.microsoft.azure.synapse.ml.lightgbm.booster.LightGBMBooster.boosterHandler$lzycompute(LightGBMBooster.scala:237)
	at com.microsoft.azure.synapse.ml.lightgbm.booster.LightGBMBooster.boosterHandler(LightGBMBooster.scala:232)
	at com.microsoft.azure.synapse.ml.lightgbm.booster.LightGBMBooster.numClasses$lzycompute(LightGBMBooster.scala:509)
	at com.microsoft.azure.synapse.ml.lightgbm.booster.LightGBMBooster.numClasses(LightGBMBooster.scala:509)
	at com.microsoft.azure.synapse.ml.lightgbm.LightGBMClassificationModel$.loadNativeModelFromFile(LightGBMClassifier.scala:202)
	at com.microsoft.azure.synapse.ml.lightgbm.LightGBMClassificationModel.loadNativeModelFromFile(LightGBMClassifier.scala)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:380)
	at py4j.Gateway.invoke(Gateway.java:306)
	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
	at py4j.commands.CallCommand.execute(CallCommand.java:79)
	at py4j.ClientServerConnection.waitForCommands(ClientServerConnection.java:195)
	at py4j.ClientServerConnection.run(ClientServerConnection.java:115)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

### What component(s) does this bug affect?

- [ ] `area/cognitive`: Cognitive project
- [ ] `area/core`: Core project
- [ ] `area/deep-learning`: DeepLearning project
- [X] `area/lightgbm`: Lightgbm project
- [ ] `area/opencv`: Opencv project
- [ ] `area/vw`: VW project
- [ ] `area/website`: Website
- [ ] `area/build`: Project build system
- [ ] `area/notebooks`: Samples under notebooks folder
- [ ] `area/docker`: Docker usage
- [ ] `area/models`: models related issue

### What language(s) does this bug affect?

- [ ] `language/scala`: Scala source code
- [X] `language/python`: Pyspark APIs
- [ ] `language/r`: R APIs
- [ ] `language/csharp`: .NET APIs
- [ ] `language/new`: Proposals for new client languages

### What integration(s) does this bug affect?

- [ ] `integrations/synapse`: Azure Synapse integrations
- [ ] `integrations/azureml`: Azure ML integrations
- [X] `integrations/databricks`: Databricks integrations

AB#1900837

**Comment by serena-ruan** [comment]
@imatiach-msft @svotaw
Hi Ilya and Scott, it seems the user encountered problems with lightgbm when loading the model saved in dbfs (trained in another cluster) but not when training in the same cluster. Would you be able to take a look at this issue? Thanks!

**Comment by svotaw** [comment]
what version are you using?  This is an error that was hopefully fixed in a recent checkin.

**Comment by svotaw** [comment]
This is the PR that I think fixed that... (checked in 1 week ago)  https://github.com/microsoft/SynapseML/pull/1575

**Comment by HXY777** [comment]
> what version are you using? This is an error that was hopefully fixed in a recent checkin.

I was using com.microsoft.azure:synapseml_2.12:0.10.0

**Comment by serena-ruan** [comment]
Hi @HXY777 please try using this version: 0.10.0-6-4868e8bf-SNAPSHOT and see if it works

**Comment by HXY777** [comment]
Thanks @serena-ruan, I'll try it out.

**Comment by HXY777** [comment]
Hi @serena-ruan, it works! Thank you for the help!
