### ISSUE TITLE
[BUG] FitMultivariateAnomaly: Py4JJavaError: An error occurred while calling o855.fit. : java.lang.NoClassDefFoundError: com/azure/core/util/logging/ClientLogger

### ISSUE THREAD

**Issue by fidelgf** [microsoft/SynapseML#1634]
### SynapseML version

0.10.0

### System information

- **Language version** : Python 3.8, Scala 2.12.15
- **Spark Version** : Spark 3.2
- **Spark Platform** : Synapse

### Describe the problem

After running the command model = estimator.fit(df) , I get the following error:

---------------------------------------------------------------------------
Py4JJavaError                             Traceback (most recent call last)
<ipython-input-12-56671211> in <module>
----> 1 model = estimator.fit(df)

/opt/spark/python/lib/pyspark.zip/pyspark/ml/base.py in fit(self, dataset, params)
    159                 return self.copy(params)._fit(dataset)
    160             else:
--> 161                 return self._fit(dataset)
    162         else:
    163             raise TypeError("Params must be either a param map or a list/tuple of param maps, "

~/cluster-env/clonedenv/lib/python3.8/site-packages/synapse/ml/cognitive/FitMultivariateAnomaly.py in _fit(self, dataset)
    652 
    653     def _fit(self, dataset):
--> 654         java_model = self._fit_java(dataset)
    655         return self._create_model(java_model)
    656 

/opt/spark/python/lib/pyspark.zip/pyspark/ml/wrapper.py in _fit_java(self, dataset)
    330         """
    331         self._transfer_params_to_java()
--> 332         return self._java_obj.fit(dataset._jdf)
    333 
    334     def _fit(self, dataset):

~/cluster-env/clonedenv/lib/python3.8/site-packages/py4j/java_gateway.py in __call__(self, *args)
   1302 
   1303         answer = self.gateway_client.send_command(command)
-> 1304         return_value = get_return_value(
   1305             answer, self.gateway_client, self.target_id, self.name)
   1306 

/opt/spark/python/lib/pyspark.zip/pyspark/sql/utils.py in deco(*a, **kw)
    109     def deco(*a, **kw):
    110         try:
--> 111             return f(*a, **kw)
    112         except py4j.protocol.Py4JJavaError as e:
    113             converted = convert_exception(e.java_exception)

~/cluster-env/clonedenv/lib/python3.8/site-packages/py4j/protocol.py in get_return_value(answer, gateway_client, target_id, name)
    324             value = OUTPUT_CONVERTER[type](answer[2:], gateway_client)
    325             if answer[1] == REFERENCE_TYPE:
--> 326                 raise Py4JJavaError(
    327                     "An error occurred while calling {0}{1}{2}.\n".
    328                     format(target_id, ".", name), value)

Py4JJavaError: An error occurred while calling o855.fit.
: java.lang.NoClassDefFoundError: com/azure/core/util/logging/ClientLogger
	at com.azure.storage.blob.BlobServiceClientBuilder.<init>(BlobServiceClientBuilder.java:55)
	at com.microsoft.azure.synapse.ml.cognitive.MADBase.getBlobContainerClient(MultivariateAnomalyDetection.scala:303)
	at com.microsoft.azure.synapse.ml.cognitive.MADBase.getBlobContainerClient$(MultivariateAnomalyDetection.scala:301)
	at com.microsoft.azure.synapse.ml.cognitive.FitMultivariateAnomaly.getBlobContainerClient(MultivariateAnomalyDetection.scala:405)
	at com.microsoft.azure.synapse.ml.cognitive.MADBase.getBlobContainerClient(MultivariateAnomalyDetection.scala:290)
	at com.microsoft.azure.synapse.ml.cognitive.MADBase.getBlobContainerClient$(MultivariateAnomalyDetection.scala:288)
	at com.microsoft.azure.synapse.ml.cognitive.FitMultivariateAnomaly.getBlobContainerClient(MultivariateAnomalyDetection.scala:405)
	at com.microsoft.azure.synapse.ml.cognitive.FitMultivariateAnomaly.$anonfun$fit$1(MultivariateAnomalyDetection.scala:492)
	at com.microsoft.azure.synapse.ml.logging.BasicLogging.logVerb(BasicLogging.scala:62)
	at com.microsoft.azure.synapse.ml.logging.BasicLogging.logVerb$(BasicLogging.scala:59)
	at com.microsoft.azure.synapse.ml.cognitive.FitMultivariateAnomaly.logVerb(MultivariateAnomalyDetection.scala:405)
	at com.microsoft.azure.synapse.ml.logging.BasicLogging.logFit(BasicLogging.scala:44)
	at com.microsoft.azure.synapse.ml.logging.BasicLogging.logFit$(BasicLogging.scala:43)
	at com.microsoft.azure.synapse.ml.cognitive.FitMultivariateAnomaly.logFit(MultivariateAnomalyDetection.scala:405)
	at com.microsoft.azure.synapse.ml.cognitive.FitMultivariateAnomaly.fit(MultivariateAnomalyDetection.scala:490)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
	at py4j.Gateway.invoke(Gateway.java:282)
	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
	at py4j.commands.CallCommand.execute(CallCommand.java:79)
	at py4j.GatewayConnection.run(GatewayConnection.java:238)
	at java.lang.Thread.run(Thread.java:750)

### Code to reproduce issue

I used the example described in the following link:

https://microsoft.github.io/SynapseML/docs/features/cognitive_services/CognitiveServices%20-%20Multivariate%20Anomaly%20Detection/

import os
from pyspark.sql import SparkSession
from synapse.ml.core.platform import find_secret

spark = SparkSession.builder.getOrCreate()

anomalyKey = find_secret("anomaly-api-key")

connectionString = find_secret("madtest-connection-string")

containerName = "intermediate-data-container-name"

location = "westus2"

import numpy as np
import pandas as pd

import pyspark
from pyspark.sql.functions import col
from pyspark.sql.functions import lit
from pyspark.sql.types import DoubleType
import matplotlib.pyplot as plt

import synapse.ml
from synapse.ml.cognitive import *

df = (
    spark.read.format("csv")
    .option("header", "true")
    .load("wasbs://publicwasb@mmlspark.blob.core.windows.net/MVAD/sample.csv")
)

df = (
    df.withColumn("sensor_1", col("sensor_1").cast(DoubleType()))
    .withColumn("sensor_2", col("sensor_2").cast(DoubleType()))
    .withColumn("sensor_3", col("sensor_3").cast(DoubleType()))
)

df.show(5)

trainingStartTime = "2020-06-01T12:00:00Z"
trainingEndTime = "2020-07-02T17:55:00Z"
intermediateSaveDir = "intermediateData"
timestampColumn = "timestamp"
inputColumns = ["sensor_1", "sensor_2", "sensor_3"]

estimator = (
    FitMultivariateAnomaly()
    .setSubscriptionKey(anomalyKey)
    .setLocation(location)
    .setStartTime(trainingStartTime)
    .setEndTime(trainingEndTime)
    .setContainerName(containerName)
    .setIntermediateSaveDir(intermediateSaveDir)
    .setTimestampCol(timestampColumn)
    .setInputCols(inputColumns)
    .setSlidingWindow(200)
    .setConnectionString(connectionString)
)

model = estimator.fit(df)

### What component(s) does this bug affect?

- [X] `area/cognitive`: Cognitive project
- [ ] `area/core`: Core project
- [ ] `area/deep-learning`: DeepLearning project
- [ ] `area/lightgbm`: Lightgbm project
- [ ] `area/opencv`: Opencv project
- [ ] `area/vw`: VW project
- [ ] `area/website`: Website
- [ ] `area/build`: Project build system
- [ ] `area/notebooks`: Samples under notebooks folder
- [ ] `area/docker`: Docker usage
- [ ] `area/models`: models related issue

### What language(s) does this bug affect?

- [ ] `language/scala`: Scala source code
- [X] `language/python`: Pyspark APIs
- [ ] `language/r`: R APIs
- [ ] `language/csharp`: .NET APIs
- [ ] `language/new`: Proposals for new client languages

### What integration(s) does this bug affect?

- [X] `integrations/synapse`: Azure Synapse integrations
- [ ] `integrations/azureml`: Azure ML integrations
- [ ] `integrations/databricks`: Databricks integrations

AB#1949336

**Comment by mhamilton723** [comment]
Hey @fidelgf please use the latest version of MVAD which now has no dependency on Azure SDKs (which is what this error is caused by)!

# SynapseML Build and Release Information
## Maven Coordinates
com.microsoft.azure:synapseml_2.12:0.10.1-7-289bd974-SNAPSHOT

## Maven Resolver
https://mmlspark.azureedge.net/maven

## Documentation Pages:
[Scala Documentation](https://mmlspark.blob.core.windows.net/docs/0.10.1-7-289bd974-SNAPSHOT/scala/index.html) 
[Python Documentation](https://mmlspark.blob.core.windows.net/docs/0.10.1-7-289bd974-SNAPSHOT/pyspark/index.html)
