### ISSUE TITLE
[BUG] TrainRegressor does not throw user friendly error message if some column has only one distinct value

### ISSUE THREAD

**Issue by dylanw-oss** [microsoft/SynapseML#1667]
### SynapseML version

0.10.1

### System information

- python 3.8, scala 2.12
- Spark 3.2.1

### Describe the problem

If our training dataset has a column with only one distinct value, we'll get an error message, which does not make sense to end user, instead of it, spark ml will give precise error message about what's wrong.
_java.lang.IllegalArgumentException: **requirement failed: VectorSlicer requires that at least one feature be selected**._

### Code to reproduce issue

This is the sample dataset to reproduce this issue.
```scala
val trainDF = spark.createDataFrame(Seq(
      (0, "2", 0.50, 0.60, 0),
      (1, "2", 0.40, 0.50, 1),
      (2, "2", 0.78, 0.99, 2),
      (3, "2", 0.12, 0.34, 3),
      (0, "2", 0.50, 0.60, 0),
      (1, "2", 0.40, 0.50, 1),
      (2, "2", 0.78, 0.99, 2),
      (3, "2", 0.12, 0.34, 3),
      (0, "2", 0.50, 0.60, 0),
      (1, "2", 0.40, 0.50, 1),
      (2, "2", 0.78, 0.99, 2),
      (3, "2", 0.12, 0.34, 3)))
      .toDF("Label", "col1", "col2", "col3", "col4")
```

If we do regression model training with spark ml and prepare featurization:
```scala
import org.apache.spark.ml.feature.StringIndexer
import org.apache.spark.ml.feature.OneHotEncoder
      
val indexer = new StringIndexer().setInputCol("col1").setOutputCol("col1_index")
val indexed = indexer.fit(trainDF).transform(trainDF)

val encoder = new OneHotEncoder().setInputCols(Array("col1_index")).setOutputCols(Array("col1_ONE"))
val encoded = encoder.fit(indexed).transform(indexed)
encoded.show()
```
We'll get clear error message:
_java.lang.IllegalArgumentException:  **requirement failed: The input column col1_index should have at least two distinct values**.
  at scala.Predef$.require(Predef.scala:281)
  at org.apache.spark.ml.feature.OneHotEncoderCommon$.$anonfun$transformOutputColumnSchema$1(OneHotEncoder.scala:491)
  at scala.Option.map(Option.scala:230)
  at org.apache.spark.ml.feature.OneHotEncoderCommon$.transformOutputColumnSchema(OneHotEncoder.scala:488)
  at org.apache.spark.ml.feature.OneHotEncoderBase.$anonfun$validateAndTransformSchema$4(OneHotEncoder.scala:98)_

But if we use SynapseML TrainRegressor:
```scala
import com.microsoft.azure.synapse.ml.train._
import org.apache.spark.ml.regression.RandomForestRegressor

val regressor = new TrainRegressor()
    .setModel(new RandomForestRegressor())
    .setLabelCol("Label")

regressor.fit(trainDF)
```

the error message is misleading:
_java.lang.IllegalArgumentException: **requirement failed: VectorSlicer requires that at least one feature be selected**.
  at scala.Predef$.require(Predef.scala:281)
  at org.apache.spark.ml.feature.VectorSlicer.transformSchema(VectorSlicer.scala:146)
  at com.microsoft.azure.synapse.ml.featurize.CountSelectorModel.transformSchema(CountSelector.scala:85)_

### What component(s) does this bug affect?

- [ ] `area/cognitive`: Cognitive project
- [ ] `area/core`: Core project
- [ ] `area/deep-learning`: DeepLearning project
- [ ] `area/lightgbm`: Lightgbm project
- [ ] `area/opencv`: Opencv project
- [ ] `area/vw`: VW project
- [ ] `area/website`: Website
- [ ] `area/build`: Project build system
- [ ] `area/notebooks`: Samples under notebooks folder
- [ ] `area/docker`: Docker usage
- [X] `area/models`: models related issue

### What language(s) does this bug affect?

- [X] `language/scala`: Scala source code
- [X] `language/python`: Pyspark APIs
- [X] `language/r`: R APIs
- [X] `language/csharp`: .NET APIs
- [ ] `language/new`: Proposals for new client languages

### What integration(s) does this bug affect?

- [ ] `integrations/synapse`: Azure Synapse integrations
- [ ] `integrations/azureml`: Azure ML integrations
- [ ] `integrations/databricks`: Databricks integrations

**Comment by mhamilton723** [comment]
Thank you for the thoughtful repro. Tagging in @imatiach-msft to take a look at this

**Comment by ranadeepsingh** [comment]
Resolved by #2629. SynapseML now treats collapsed constant/empty text features as valid zero-width vectors when useful sibling features remain, preserves null/schema behavior, and fails early with a clear column-specific message when every requested feature collapses. The merged coverage includes CountSelector/Featurize, generated Python, model training, persistence, missing numeric compatibility, and Spark 4.1 replay.
