### ISSUE TITLE
[BUG] SpeechToTextSDK transformer fails with MP3 input on with SPXERR_GSTREAMER_NOT_FOUND_ERROR

### ISSUE THREAD

**Issue by kharigardner** [microsoft/SynapseML#1694]
### SynapseML version

0.10.1-22-95f451ab-SNAPSHOT

### System information

- **Language version**: Python 3.8
- **Spark Version** (e.g. 3.2.2): 3.2
- **Spark Platform** (e.g. Synapse, Databricks): Synapse

### Describe the problem

Attempting to transform a spark dataframe that contains a audio column containing mp3 audio bytes to text.
When using the SpeechToTextSDK transformer, it always returns the following error:

Py4JJavaError: An error occurred while calling z:com.microsoft.spark.notebook.visualization.display.getDisplayResultForIPython.
: org.apache.spark.SparkException: Job aborted due to stage failure: Task 0 in stage 2.0 failed 4 times, most recent failure: Lost task 0.3 in stage 2.0 (TID 24) (vm-f5077682 executor 2): java.lang.IllegalArgumentException: Exception with an error code: 0x29 (SPXERR_GSTREAMER_NOT_FOUND_ERROR)

### Code to reproduce issue

```python
stt = (SpeechToTextSDK()
    .setSubscriptionKey(mssparkutils.credentials.getSecret(akvName="foofoo", secret='foofoo',linkedService="foofoo"))
    .setLocation("eastus")
    .setFileType ("mp3")
    .setOutputCol('text')
    .setAudioDataCol('audio')
    .setLanguage('en-US'))

### Other info / logs

```python-traceback
Py4JJavaError                             Traceback (most recent call last)
<ipython-input-12-57b3b446> in <module>
----> 1 display(transformed_df)

~/cluster-env/env/lib/python3.8/site-packages/notebookutils/visualization/display.py in display(data, summary)
    197         log4jLogger \
    198             .error(f"display failed with error, language: python, error: {err}")
--> 199         raise err
    200 
    201     log4jLogger \

~/cluster-env/env/lib/python3.8/site-packages/notebookutils/visualization/display.py in display(data, summary)
    176                     from IPython.display import publish_display_data
    177                     publish_display_data({
--> 178                         "application/vnd.synapse.display-widget+json": sc._jvm.display.getDisplayResultForIPython(
    179                             df._jdf, summary)
    180                     })

~/cluster-env/env/lib/python3.8/site-packages/py4j/java_gateway.py in __call__(self, *args)
   1319 
   1320         answer = self.gateway_client.send_command(command)
-> 1321         return_value = get_return_value(
   1322             answer, self.gateway_client, self.target_id, self.name)
   1323 

/opt/spark/python/lib/pyspark.zip/pyspark/sql/utils.py in deco(*a, **kw)
    109     def deco(*a, **kw):
    110         try:
--> 111             return f(*a, **kw)
    112         except py4j.protocol.Py4JJavaError as e:
    113             converted = convert_exception(e.java_exception)

~/cluster-env/env/lib/python3.8/site-packages/py4j/protocol.py in get_return_value(answer, gateway_client, target_id, name)
    324             value = OUTPUT_CONVERTER[type](answer[2:], gateway_client)
    325             if answer[1] == REFERENCE_TYPE:
--> 326                 raise Py4JJavaError(
    327                     "An error occurred while calling {0}{1}{2}.\n".
    328                     format(target_id, ".", name), value)

Py4JJavaError: An error occurred while calling z:com.microsoft.spark.notebook.visualization.display.getDisplayResultForIPython.
: org.apache.spark.SparkException: Job aborted due to stage failure: Task 0 in stage 2.0 failed 4 times, most recent failure: Lost task 0.3 in stage 2.0 (TID 24) (vm-f5077682 executor 2): java.lang.IllegalArgumentException: Exception with an error code: 0x29 (SPXERR_GSTREAMER_NOT_FOUND_ERROR)
	at com.microsoft.cognitiveservices.speech.util.Contracts.throwIfFail(Contracts.java:121)
	at com.microsoft.cognitiveservices.speech.SpeechRecognizer.<init>(SpeechRecognizer.java:66)
	at com.microsoft.azure.synapse.ml.cognitive.SpeechToTextSDK.inputStreamToText(SpeechToTextSDK.scala:444)
	at com.microsoft.azure.synapse.ml.cognitive.SpeechSDKBase.$anonfun$transformAudioRows$1(SpeechToTextSDK.scala:326)
	at scala.collection.Iterator$$anon$11.nextCur(Iterator.scala:486)
	at scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:492)
	at scala.collection.Iterator$$anon$10.hasNext(Iterator.scala:460)
	at org.apache.spark.sql.catalyst.expressions.GeneratedClass$GeneratedIteratorForCodegenStage2.processNext(Unknown Source)
	at org.apache.spark.sql.execution.BufferedRowIterator.hasNext(BufferedRowIterator.java:43)
	at org.apache.spark.sql.execution.WholeStageCodegenExec$$anon$1.hasNext(WholeStageCodegenExec.scala:760)
	at org.apache.spark.sql.execution.SparkPlan.$anonfun$getByteArrayRdd$1(SparkPlan.scala:386)
	at org.apache.spark.rdd.RDD.$anonfun$mapPartitionsInternal$2(RDD.scala:905)
	at org.apache.spark.rdd.RDD.$anonfun$mapPartitionsInternal$2$adapted(RDD.scala:905)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:57)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:374)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:338)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:90)
	at org.apache.spark.scheduler.Task.run(Task.scala:131)
	at org.apache.spark.executor.Executor$TaskRunner.$anonfun$run$3(Executor.scala:506)
	at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1491)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:509)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:750)

Driver stacktrace:
	at org.apache.spark.scheduler.DAGScheduler.failJobAndIndependentStages(DAGScheduler.scala:2464)
	at org.apache.spark.scheduler.DAGScheduler.$anonfun$abortStage$2(DAGScheduler.scala:2413)
	at org.apache.spark.scheduler.DAGScheduler.$anonfun$abortStage$2$adapted(DAGScheduler.scala:2412)
	at scala.collection.mutable.ResizableArray.foreach(ResizableArray.scala:62)
	at scala.collection.mutable.ResizableArray.foreach$(ResizableArray.scala:55)
	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:49)
	at org.apache.spark.scheduler.DAGScheduler.abortStage(DAGScheduler.scala:2412)
	at org.apache.spark.scheduler.DAGScheduler.$anonfun$handleTaskSetFailed$1(DAGScheduler.scala:1168)
	at org.apache.spark.scheduler.DAGScheduler.$anonfun$handleTaskSetFailed$1$adapted(DAGScheduler.scala:1168)
	at scala.Option.foreach(Option.scala:407)
	at org.apache.spark.scheduler.DAGScheduler.handleTaskSetFailed(DAGScheduler.scala:1168)
	at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.doOnReceive(DAGScheduler.scala:2652)
	at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.onReceive(DAGScheduler.scala:2594)
	at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.onReceive(DAGScheduler.scala:2583)
	at org.apache.spark.util.EventLoop$$anon$1.run(EventLoop.scala:49)
	at org.apache.spark.scheduler.DAGScheduler.runJob(DAGScheduler.scala:944)
	at org.apache.spark.SparkContext.runJob(SparkContext.scala:2318)
	at org.apache.spark.SparkContext.runJob(SparkContext.scala:2339)
	at org.apache.spark.SparkContext.runJob(SparkContext.scala:2358)
	at org.apache.spark.sql.execution.SparkPlan.executeTake(SparkPlan.scala:528)
	at org.apache.spark.sql.execution.SparkPlan.executeTake(SparkPlan.scala:481)
	at org.apache.spark.sql.execution.CollectLimitExec.executeCollect(limit.scala:48)
	at org.apache.spark.sql.Dataset.collectFromPlan(Dataset.scala:3728)
	at org.apache.spark.sql.Dataset.$anonfun$head$1(Dataset.scala:2741)
	at org.apache.spark.sql.Dataset.$anonfun$withAction$1(Dataset.scala:3719)
	at org.apache.spark.sql.execution.SQLExecution$.$anonfun$withNewExecutionId$5(SQLExecution.scala:104)
	at org.apache.spark.sql.execution.SQLExecution$.withSQLConfPropagated(SQLExecution.scala:169)
	at org.apache.spark.sql.execution.SQLExecution$.$anonfun$withNewExecutionId$1(SQLExecution.scala:91)
	at org.apache.spark.sql.SparkSession.withActive(SparkSession.scala:775)
	at org.apache.spark.sql.execution.SQLExecution$.withNewExecutionId(SQLExecution.scala:65)
	at org.apache.spark.sql.Dataset.withAction(Dataset.scala:3717)
	at org.apache.spark.sql.Dataset.head(Dataset.scala:2741)
	at org.apache.spark.sql.Dataset.take(Dataset.scala:2948)
	at org.apache.spark.sql.GetRowsHelper$.getRowsInJsonString(GetRowsHelper.scala:51)
	at com.microsoft.spark.notebook.visualization.display$.generateTableConfig(Display.scala:471)
	at com.microsoft.spark.notebook.visualization.display$.exec(Display.scala:205)
	at com.microsoft.spark.notebook.visualization.display$.getDisplayResultInternal(Display.scala:148)
	at com.microsoft.spark.notebook.visualization.display$.getDisplayResultForIPython(Display.scala:87)
	at com.microsoft.spark.notebook.visualization.display.getDisplayResultForIPython(Display.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
	at py4j.Gateway.invoke(Gateway.java:282)
	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
	at py4j.commands.CallCommand.execute(CallCommand.java:79)
	at py4j.GatewayConnection.run(GatewayConnection.java:238)
	at java.lang.Thread.run(Thread.java:750)
Caused by: java.lang.IllegalArgumentException: Exception with an error code: 0x29 (SPXERR_GSTREAMER_NOT_FOUND_ERROR)
	at com.microsoft.cognitiveservices.speech.util.Contracts.throwIfFail(Contracts.java:121)
	at com.microsoft.cognitiveservices.speech.SpeechRecognizer.<init>(SpeechRecognizer.java:66)
	at com.microsoft.azure.synapse.ml.cognitive.SpeechToTextSDK.inputStreamToText(SpeechToTextSDK.scala:444)
	at com.microsoft.azure.synapse.ml.cognitive.SpeechSDKBase.$anonfun$transformAudioRows$1(SpeechToTextSDK.scala:326)
	at scala.collection.Iterator$$anon$11.nextCur(Iterator.scala:486)
	at scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:492)
	at scala.collection.Iterator$$anon$10.hasNext(Iterator.scala:460)
	at org.apache.spark.sql.catalyst.expressions.GeneratedClass$GeneratedIteratorForCodegenStage2.processNext(Unknown Source)
	at org.apache.spark.sql.execution.BufferedRowIterator.hasNext(BufferedRowIterator.java:43)
	at org.apache.spark.sql.execution.WholeStageCodegenExec$$anon$1.hasNext(WholeStageCodegenExec.scala:760)
	at org.apache.spark.sql.execution.SparkPlan.$anonfun$getByteArrayRdd$1(SparkPlan.scala:386)
	at org.apache.spark.rdd.RDD.$anonfun$mapPartitionsInternal$2(RDD.scala:905)
	at org.apache.spark.rdd.RDD.$anonfun$mapPartitionsInternal$2$adapted(RDD.scala:905)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:57)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:374)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:338)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:90)
	at org.apache.spark.scheduler.Task.run(Task.scala:131)
	at org.apache.spark.executor.Executor$TaskRunner.$anonfun$run$3(Executor.scala:506)
	at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1491)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:509)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)

### What component(s) does this bug affect?

- [X] `area/cognitive`: Cognitive project
- [ ] `area/core`: Core project
- [ ] `area/deep-learning`: DeepLearning project
- [ ] `area/lightgbm`: Lightgbm project
- [ ] `area/opencv`: Opencv project
- [ ] `area/vw`: VW project
- [ ] `area/website`: Website
- [ ] `area/build`: Project build system
- [ ] `area/notebooks`: Samples under notebooks folder
- [ ] `area/docker`: Docker usage
- [ ] `area/models`: models related issue

### What language(s) does this bug affect?

- [ ] `language/scala`: Scala source code
- [X] `language/python`: Pyspark APIs
- [ ] `language/r`: R APIs
- [ ] `language/csharp`: .NET APIs
- [ ] `language/new`: Proposals for new client languages

### What integration(s) does this bug affect?

- [X] `integrations/synapse`: Azure Synapse integrations
- [ ] `integrations/azureml`: Azure ML integrations
- [ ] `integrations/databricks`: Databricks integrations

**Comment by BrendanWalsh** [comment]
Hi @kharigardner!

The Speech SDK uses a library called GStreamer to handle compressed audio like mp3s, but for licensing reasons those binaries aren't included in either the Speech SDK or SynapseML. More information is available [In the Speech SDK docs](https://learn.microsoft.com/en-us/azure/cognitive-services/speech-service/how-to-use-codec-compressed-audio-input-streams?tabs=linux%2Cdebian%2Cjava-android%2Cterminal&pivots=programming-language-csharp).

You'll need to install a GStreamer distribution so it's available by your Spark pools on Synapse at runtime.

Thanks,
Brendan
