### ISSUE TITLE
ModuleNotFoundError: No module named 'mmlspark.lightgbm._LightGBMClassifier' 

### ISSUE THREAD

**Issue by TomasZhang19** [microsoft/SynapseML#1767]
python 3.6.5
spark version 2.3.2
mmlspark-v1.0.0-rc

cd ../SynapseML-mmlspark-v1.0.0-rc1/src/main/python
python setup.py install
pyspark
from mmlspark.lightgbm import LightGBMRegressor

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File ".../SynapseML-mmlspark-v1.0.0-rc1/src/main/python/mmlspark/lightgbm/LightGBMClassifier.py", line 11, in <module>
    from mmlspark.lightgbm._LightGBMClassifier import _LightGBMClassifier
ModuleNotFoundError: No module named 'mmlspark.lightgbm._LightGBMClassifier' 

Could you please tell me how to solve this error?

**Comment by TomFinley** [comment]
Hi @TomasZhang19 , I gather that this was intended to be a followup to #1764 ?

Just to lead off with the first note, the process you are describing is not the intended usage. You appear to have downloaded the repository, gone into the source, have `cd`ed into the source directory where the Python code is at `/src/python`, and are attempting to run the package from there. This will not work, for a variety of reasons that are probably not that interesting to explore. Instead let's try following the instructions that do exist, starting with `1.0.0-rc1` and failing that, as we shall see, with a prior version.

Note the setup and installation documentation [tagged as being the `mmlspark` 1.0.0-rc1](https://github.com/microsoft/SynapseML/tree/8d31c026a252677654717768e942e1cf1adc9082#setup-and-installation), which you specifically be attempting to use, do not appear to work. Indeed, [the Maven repository lists only two versions of the old library](https://mvnrepository.com/artifact/com.microsoft.ml.spark/mmlspark), 0.18.1 and 0.18.0. Possibly contributors to this project will know whether and why those `1rc` versions were removed -- at any rate, I do not know, but whatever the reason, they're just not there. Anyway, let's try 0.18.1, since that *is* there.

The `mmlspark` version 0.18.1 [setup and installation instructions](https://github.com/microsoft/SynapseML/tree/62946d1adf7baa4817f54f6c166db38cea9900db#setup-and-installation) do appear to work.

So just to set up my environment so that it is somewhat close to yours (on Ubuntu 18.04 using `conda`) as so (you obviously don't have to do this, just explaining how I tried to re-create your setup):

```bash
conda create --name tomasz python=3.6 pyspark=2.3.2
conda activate tomasz
```

Then, I followed one of the instructions on installation. This is just the first one, you'll note that the documentation has others.

```bash
pyspark --packages com.microsoft.ml.spark:mmlspark_2.11:0.18.1
```

Here is an example of usage within `pyspark`, after created using 0.18.1.

```python
import mmlspark.lightgbm as lgbm
estimator = lgbm.LightGBMClassifier()
estimator.fit(...)
```

Obviously doing other things instead of and preceeding the `...` to load and prepare whatever dataset you're trying to learn over.

**Comment by ranadeepsingh** [comment]
Closing as unsupported environment. Legacy mmlspark packages, Spark 2.x, and Python 3.6 are no longer supported. Modern SynapseML releases require Spark 3.2+ and Python 3.8+ installed via Maven coordinates com.microsoft.azure:synapseml_2.12 or PyPI synapseml.
