### ISSUE TITLE
 Azure Key Vault returned error code 'Unauthorized' with message 'AKV10032: Invalid issuer

### ISSUE THREAD

**Issue by ShanthiTV** [microsoft/SynapseML#1923]
Have installed Synapse ML(Used the code given for Spark 3.2 pool) and updated the code in the notebook to point to the Azure OpenAI service and deployment name. Also, updated the key as a string. But on Running the cell, getting the error, **Azure Key Vault returned error code 'Unauthorized' with message 'AKV10032: Invalid issuer**

Is using keyvault mandatory instead of using the key directly as a string? Because, looks like the code internally looks for the keyvault value.( getSecret(keyvault, secret_name))

Spark version - Spark 3.3

Pasting below the full error message.

---------------------------------------------------------------------------
Py4JJavaError                             Traceback (most recent call last)
Cell In [31], line 17
     14 deployment_name_embeddings = "text-search-ada-doc-001"
     15 deployment_name_embeddings_query = "text-search-ada-query-001"
---> 17 key = find_secret("0155c35431234de")  # please replace this with your key as a string
     19 assert key is not None and service_name is not None

File /mnt/var/hadoop/tmp/nm-local-dir/usercache/trusted-service-user/appcache/application_1681810270972_0001/container_1681810270972_0001_01_000001/synapseml-core_2.12-0.11.0.jar/synapse/ml/core/platform/Platform.py:56, in find_secret(secret_name, keyvault, override)
     53 if running_on_synapse():
     54     from notebookutils.mssparkutils.credentials import getSecret
---> 56     return getSecret(keyvault, secret_name)
     57 elif running_on_databricks():
     58     from pyspark.sql import SparkSession

File ~/cluster-env/env/lib/python3.10/site-packages/notebookutils/mssparkutils/credentials.py:21, in getSecret(akvName, secret, linkedService)
     19 def getSecret(akvName, secret, linkedService=''):
     20     if linkedService == '':
---> 21         return creds.getSecret(akvName, secret)
     22     else:
     23         return creds.getSecret(akvName, secret, linkedService)

File ~/cluster-env/env/lib/python3.10/site-packages/py4j/java_gateway.py:1321, in JavaMember.__call__(self, *args)
   1315 command = proto.CALL_COMMAND_NAME +\
   1316     self.command_header +\
   1317     args_command +\
   1318     proto.END_COMMAND_PART
   1320 answer = self.gateway_client.send_command(command)
-> 1321 return_value = get_return_value(
   1322     answer, self.gateway_client, self.target_id, self.name)
   1324 for temp_arg in temp_args:
   1325     temp_arg._detach()

File /opt/spark/python/lib/pyspark.zip/pyspark/sql/utils.py:190, in capture_sql_exception.<locals>.deco(*a, **kw)
    188 def deco(*a: Any, **kw: Any) -> Any:
    189     try:
--> 190         return f(*a, **kw)
    191     except Py4JJavaError as e:
    192         converted = convert_exception(e.java_exception)

File ~/cluster-env/env/lib/python3.10/site-packages/py4j/protocol.py:326, in get_return_value(answer, gateway_client, target_id, name)
    324 value = OUTPUT_CONVERTER[type](answer[2:], gateway_client)
    325 if answer[1] == REFERENCE_TYPE:
--> 326     raise Py4JJavaError(
    327         "An error occurred while calling {0}{1}{2}.\n".
    328         format(target_id, ".", name), value)
    329 else:
    330     raise Py4JError(
    331         "An error occurred while calling {0}{1}{2}. Trace:\n{3}\n".
    332         format(target_id, ".", name, value))

Py4JJavaError: An error occurred while calling z:mssparkutils.credentials.getSecret.
: com.microsoft.azure.synapse.tokenlibrary.utils.AkvUtils$KeyVaultException: Azure Key Vault returned error code 'Unauthorized' with message 'AKV10032: Invalid issuer. Expected one of https://sts.windows.net/72f988bf-86f1-41af-91ab-2d7cd011db47/, https://sts.windows.net/f8cdef31-a31e-4b4a-93e4-5f571e91255a/, https://sts.windows.net/e2d54eb5-3869-4f70-8578-dee5fc7331f4/, https://sts.windows.net/33e01921-4d64-4f8c-a055-5bdaffd5e33d/, https://sts.windows.net/975f013f-7f24-47e8-a7d3-abc4752bf346/, found https://sts.windows.net/a6ca95a9-7d2f-4ecb-b715-381d58ca2dbd/.' and inner error 'None'
	at com.microsoft.azure.synapse.tokenlibrary.utils.AkvUtils$KeyVaultErrorResponse.toException(AkvUtils.scala:71)
	at com.microsoft.azure.synapse.tokenlibrary.utils.AkvUtils$.$anonfun$performAkvRequest$3(AkvUtils.scala:97)
	at scala.util.Success.$anonfun$map$1(Try.scala:255)
	at scala.util.Success.map(Try.scala:213)
	at com.microsoft.azure.synapse.tokenlibrary.utils.AkvUtils$.$anonfun$performAkvRequest$1(AkvUtils.scala:97)
	at com.twitter.util.Future.$anonfun$flatMap$1(Future.scala:1808)
	at com.twitter.util.Promise$FutureTransformer.liftedTree1$1(Promise.scala:240)
	at com.twitter.util.Promise$FutureTransformer.k(Promise.scala:240)
	at com.twitter.util.Promise$Transformer.apply(Promise.scala:215)
	at com.twitter.util.Promise$WaitQueue.com$twitter$util$Promise$WaitQueue$$run(Promise.scala:91)
	at com.twitter.util.Promise$WaitQueue$$anon$1.run(Promise.scala:86)
	at com.twitter.concurrent.LocalScheduler$Activation.run(Scheduler.scala:198)
	at com.twitter.concurrent.LocalScheduler$Activation.submit(Scheduler.scala:157)
	at com.twitter.concurrent.LocalScheduler.submit(Scheduler.scala:274)
	at com.twitter.concurrent.Scheduler$.submit(Scheduler.scala:109)
	at com.twitter.util.Promise$WaitQueue.runInScheduler(Promise.scala:86)
	at com.twitter.util.Promise.updateIfEmpty(Promise.scala:778)
	at com.twitter.util.Promise.update(Promise.scala:750)
	at com.twitter.util.Promise.setValue(Promise.scala:726)
	at com.twitter.concurrent.AsyncQueue.offer(AsyncQueue.scala:123)
	at com.twitter.finagle.netty4.transport.ChannelTransport$$anon$2.channelRead(ChannelTransport.scala:168)
	at shadenetty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at shadenetty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at shadenetty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at com.twitter.finagle.netty4.http.handler.UnpoolHttpHandler$.channelRead(UnpoolHttpHandler.scala:32)
	at shadenetty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at shadenetty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at shadenetty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at com.twitter.finagle.netty4.http.handler.ClientExceptionMapper$.channelRead(ClientExceptionMapper.scala:35)
	at shadenetty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at shadenetty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at shadenetty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at com.twitter.finagle.netty4.http.handler.HeaderValidatorHandler$.channelRead(HeaderValidatorHandler.scala:51)
	at shadenetty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at shadenetty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at shadenetty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at shadenetty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)
	at shadenetty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at shadenetty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at shadenetty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at shadenetty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)
	at shadenetty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at shadenetty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at shadenetty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at shadenetty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:438)
	at shadenetty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:323)
	at shadenetty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:297)
	at shadenetty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:253)
	at shadenetty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at shadenetty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at shadenetty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at shadenetty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86)
	at shadenetty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at shadenetty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at shadenetty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at shadenetty.handler.ssl.SslHandler.unwrap(SslHandler.java:1432)
	at shadenetty.handler.ssl.SslHandler.decodeJdkCompatible(SslHandler.java:1199)
	at shadenetty.handler.ssl.SslHandler.decode(SslHandler.java:1243)
	at shadenetty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:502)
	at shadenetty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:441)
	at shadenetty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:278)
	at shadenetty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at shadenetty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at shadenetty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at shadenetty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1434)
	at shadenetty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at shadenetty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at shadenetty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:965)
	at shadenetty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163)
	at shadenetty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:648)
	at shadenetty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:583)
	at shadenetty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:500)
	at shadenetty.channel.nio.NioEventLoop.run(NioEventLoop.java:462)
	at shadenetty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:897)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at com.twitter.finagle.util.BlockingTimeTrackingThreadFactory$$anon$1.run(BlockingTimeTrackingThreadFactory.scala:23)
	at shadenetty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:750)

**Comment by ShanthiTV** [comment]
Closing the issue since opened under a wrong label.
