### ISSUE TITLE
[BUG] Unable to score using .transform() after converting model from ebm to onnx

### ISSUE THREAD

**Issue by ANNIKADAHLMANN-8451** [microsoft/SynapseML#2039]
### SynapseML version

0.11.2

### System information

- **Language version** (e.g. python 3.9.5, scala 2.12)
- **Spark Version** (e.g. 3.3.2)
- **Spark Platform** (e.g. Synapse, Databricks)

### Describe the problem

After loading in sklearn's iris dataset and manually adding null values (`numpy.nan`), I am unable to score as expected on a heldout test set. I am using `ebm2onnx.to_onnx()` to convert a `ExplainableBoostingClassifier()` to an ONNX model then using `.transform()` on a pyspark heldout dataset. EBM's internally handle missing values by creating a separate bin in each tree. For a pyspark dataset that doesn't have any null values, this functionality works as expected. However, as soon as there are null values, the `.transform()` function runs successfully but then any manipulation of the newly added 'probability' column, results in error. I am able to successfully run scoring on the dataframe that DOES contain null values using EBM's directly (`ebm.predict_proba()`) and using ONNX Runtime, which I'll include examples in the "PROPER BEHAVIOR" code section below.

### Code to reproduce issue

**BUG BEHAVIOR**
Imports
```
import numpy as np
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split

import onnx
import ebm2onnx
from interpret.glassbox import ExplainableBoostingClassifier
from synapse.ml.onnx import ONNXModel
```

Load the Iris toy dataset and add null values:

```
def add_null_values(df, perc_null):
  for col in df.columns:
    df.loc[list(df[col].sample(frac=0.1).index), col] = np.nan
  return df
```

```
X, y = load_iris(return_X_y=True, as_frame=True)
X = add_null_values(X, 0.1)
```

Split the dataset into train and test:
```
seed = 42
np.random.seed(seed)

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20, random_state=seed)
```

Check the number of null values in the dataset:
`X_test.isna().sum()`

```
Out[37]: sepal length (cm)    4
sepal width (cm)     3
petal length (cm)    1
petal width (cm)     4
dtype: int64
```

Create EBM model, convert to onnx, and attempt to score on pyspark dataframe:
```
def convert_model(model, input_df):
    onnx_model = ebm2onnx.to_onnx(
        model,
        ebm2onnx.get_dtype_from_pandas(input_df),
        predict_proba=True
    )
    onnx_model.ir_version = 4 
    return onnx_model.SerializeToString()
```

In the below code, I do get a warning which I will copy in the 'Other info / logs' section.
```
ebm = ExplainableBoostingClassifier()
ebm.fit(X_train, y_train)
```

```
onnx_payload = convert_model(ebm, X_train)
onnx_model = ONNXModel().setModelPayload(onnx_payload)

onnx_model = (
    onnx_model.setDeviceType("CPU")
    .setFeedDict(dict(zip(X_test.columns, X_test.columns)))
    .setFetchDict({"probability": "probabilities", "prediction": "prediction"})
    .setMiniBatchSize(5000)
)
```

```
X_test_spark = spark.createDataFrame(X_test)
y_pred_spark = onnx_model.transform(X_test_spark)
```

```
print(y_pred_spark.dtypes)
OUTPUT [('sepal length (cm)', 'double'), ('sepal width (cm)', 'double'), ('petal length (cm)', 'double'), ('petal width (cm)', 'double'), ('prediction', 'bigint'), ('probability', 'array<float>')]
```

WHERE THE ERROR OCCURS, copied in 'Other info / logs' below:

`y_pred_spark.display()`

**PROPER BEHAVIOR: if X did not have any null values and running same steps as above**

`y_pred_spark.display()`
<img width="1248" alt="Screenshot 2023-08-02 at 11 28 36 AM" src="https://github.com/microsoft/SynapseML/assets/107887589/1b550f1f-70cb-4b67-b251-25d0a9d38563">

Results from running `.predict()` on the EBM model directly where `X_test` DOES have null values and the ebm was trained with a dataframe that has null values:

```
y_pred_ebm = ebm.predict(X_test)
Out[58]: array([1, 0, 2, 1, 1, 0, 1, 2, 1, 2, 2, 0, 0, 0, 0, 1, 2, 1, 1, 2, 0, 2,
       0, 2, 2, 2, 2, 2, 0, 0])
```

Results from running ONNX Runtime, note the different `convert_model` function and `X_train` and `X_test` DOES have null values:

```
def convert_model(model, input_df):
    onnx_model = ebm2onnx.to_onnx(
        model,
        ebm2onnx.get_dtype_from_pandas(input_df),
        predict_proba=True
    )
    return onnx_model
```

`onnx_rt_model = convert_model(ebm, X_train)`

_, filename = tempfile.mkstemp()
onnx.save_model(onnx_rt_model, filename)

```
sess = rt.InferenceSession(filename)
y_pred_rt = sess.run(None, {
    'sepal length (cm)': X_test['sepal length (cm)'].values,
    'sepal width (cm)': X_test['sepal width (cm)'].values,
    'petal length (cm)': X_test['petal length (cm)'].values,
    'petal width (cm)': X_test['petal width (cm)'].values,
})
y_pred_rt[0]
```
```
Out[88]: array([1, 0, 2, 1, 1, 0, 1, 2, 1, 2, 2, 0, 0, 0, 0, 1, 2, 1, 1, 2, 0, 2,
       0, 2, 2, 2, 2, 2, 0, 0], dtype=int64)
```

### Other info / logs

Warning from fitting an EBM model that has null values in the dataset:

```
/local_disk0/.ephemeral_nfs/envs/pythonEnv-f54a3c0a-9cbd-4413-b9d9-7239f88a7a65/lib/python3.9/site-packages/interpret/glassbox/_ebm/_ebm.py:666: UserWarning: Missing values detected. Our visualizations do not currently display missing values. To retain the glassbox nature of the model you need to either set the missing values to an extreme value like -1000 that will be visible on the graphs, or manually examine the missing value score in ebm.term_scores_[term_index][0]
  warn(
/local_disk0/.ephemeral_nfs/envs/pythonEnv-f54a3c0a-9cbd-4413-b9d9-7239f88a7a65/lib/python3.9/site-packages/interpret/glassbox/_ebm/_ebm.py:928: UserWarning: Detected multiclass problem. Forcing interactions to 0. Multiclass interactions work except for global visualizations, so the break statement below that disables multiclass interactions can be removed.
  warn(
```

Error when displaying null onnx predictions:

`IllegalArgumentException: Expected 1 batch elements but found 0. Expected shape is [1].`

```
org.apache.spark.SparkException: Job aborted due to stage failure: Task 13 in stage 2.0 failed 4 times, most recent failure: Lost task 13.3 in stage 2.0 (TID 33) (10.2.64.199 executor 3): java.lang.IllegalArgumentException: Expected 1 batch elements but found 0. Expected shape is [1].
	at com.microsoft.azure.synapse.ml.onnx.ONNXUtils$.assertBufferElementsWritten(ONNXUtils.scala:207)
	at com.microsoft.azure.synapse.ml.onnx.ONNXUtils$.loadTensorBuffer(ONNXUtils.scala:168)
	at com.microsoft.azure.synapse.ml.onnx.ONNXUtils$.createTensor(ONNXUtils.scala:106)
	at com.microsoft.azure.synapse.ml.onnx.ONNXRuntime$.$anonfun$applyModel$2(ONNXRuntime.scala:74)
	at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:286)
	at scala.collection.Iterator.foreach(Iterator.scala:943)
	at scala.collection.Iterator.foreach$(Iterator.scala:943)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1431)
	at scala.collection.IterableLike.foreach(IterableLike.scala:74)
	at scala.collection.IterableLike.foreach$(IterableLike.scala:73)
	at scala.collection.AbstractIterable.foreach(Iterable.scala:56)
	at scala.collection.TraversableLike.map(TraversableLike.scala:286)
	at scala.collection.TraversableLike.map$(TraversableLike.scala:279)
	at scala.collection.AbstractTraversable.map(Traversable.scala:108)
	at com.microsoft.azure.synapse.ml.onnx.ONNXRuntime$.$anonfun$applyModel$1(ONNXRuntime.scala:67)
	at scala.collection.Iterator$$anon$10.next(Iterator.scala:461)
	at com.microsoft.azure.synapse.ml.core.utils.CloseableIterator.next(CloseableIterator.scala:11)
	at scala.collection.Iterator$$anon$10.next(Iterator.scala:461)
	at scala.collection.Iterator$$anon$10.next(Iterator.scala:461)
	at scala.collection.Iterator$$anon$11.nextCur(Iterator.scala:486)
	at scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:492)
	at scala.collection.Iterator$$anon$10.hasNext(Iterator.scala:460)
	at org.apache.spark.sql.catalyst.expressions.GeneratedClass$GeneratedIteratorForCodegenStage2.processNext(Unknown Source)
	at org.apache.spark.sql.execution.BufferedRowIterator.hasNext(BufferedRowIterator.java:43)
	at org.apache.spark.sql.execution.WholeStageCodegenExec$$anon$1.hasNext(WholeStageCodegenExec.scala:761)
	at org.apache.spark.sql.execution.collect.UnsafeRowBatchUtils$.encodeUnsafeRows(UnsafeRowBatchUtils.scala:82)
	at org.apache.spark.sql.execution.collect.Collector.$anonfun$processFunc$1(Collector.scala:208)
	at org.apache.spark.scheduler.ResultTask.$anonfun$runTask$3(ResultTask.scala:75)
	at com.databricks.spark.util.ExecutorFrameProfiler$.record(ExecutorFrameProfiler.scala:110)
	at org.apache.spark.scheduler.ResultTask.$anonfun$runTask$1(ResultTask.scala:75)
	at com.databricks.spark.util.ExecutorFrameProfiler$.record(ExecutorFrameProfiler.scala:110)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:55)
	at org.apache.spark.scheduler.Task.doRunTask(Task.scala:174)
	at org.apache.spark.scheduler.Task.$anonfun$run$5(Task.scala:142)
	at com.databricks.unity.EmptyHandle$.runWithAndClose(UCSHandle.scala:125)
	at org.apache.spark.scheduler.Task.$anonfun$run$1(Task.scala:142)
	at com.databricks.spark.util.ExecutorFrameProfiler$.record(ExecutorFrameProfiler.scala:110)
	at org.apache.spark.scheduler.Task.run(Task.scala:97)
	at org.apache.spark.executor.Executor$TaskRunner.$anonfun$run$13(Executor.scala:904)
	at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1713)
	at org.apache.spark.executor.Executor$TaskRunner.$anonfun$run$4(Executor.scala:907)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
	at com.databricks.spark.util.ExecutorFrameProfiler$.record(ExecutorFrameProfiler.scala:110)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:761)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:750)

Driver stacktrace:
	at org.apache.spark.scheduler.DAGScheduler.failJobAndIndependentStages(DAGScheduler.scala:3381)
	at org.apache.spark.scheduler.DAGScheduler.$anonfun$abortStage$2(DAGScheduler.scala:3313)
	at org.apache.spark.scheduler.DAGScheduler.$anonfun$abortStage$2$adapted(DAGScheduler.scala:3304)
	at scala.collection.mutable.ResizableArray.foreach(ResizableArray.scala:62)
	at scala.collection.mutable.ResizableArray.foreach$(ResizableArray.scala:55)
	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:49)
	at org.apache.spark.scheduler.DAGScheduler.abortStage(DAGScheduler.scala:3304)
	at org.apache.spark.scheduler.DAGScheduler.$anonfun$handleTaskSetFailed$1(DAGScheduler.scala:1433)
	at org.apache.spark.scheduler.DAGScheduler.$anonfun$handleTaskSetFailed$1$adapted(DAGScheduler.scala:1433)
	at scala.Option.foreach(Option.scala:407)
	at org.apache.spark.scheduler.DAGScheduler.handleTaskSetFailed(DAGScheduler.scala:1433)
	at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.doOnReceive(DAGScheduler.scala:3593)
	at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.onReceive(DAGScheduler.scala:3531)
	at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.onReceive(DAGScheduler.scala:3519)
	at org.apache.spark.util.EventLoop$$anon$1.run(EventLoop.scala:51)
	at org.apache.spark.scheduler.DAGScheduler.$anonfun$runJob$1(DAGScheduler.scala:1182)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
	at com.databricks.spark.util.FrameProfiler$.record(FrameProfiler.scala:80)
	at org.apache.spark.scheduler.DAGScheduler.runJob(DAGScheduler.scala:1170)
	at org.apache.spark.SparkContext.runJobInternal(SparkContext.scala:2750)
	at org.apache.spark.sql.execution.collect.Collector.$anonfun$runSparkJobs$1(Collector.scala:349)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
	at com.databricks.spark.util.FrameProfiler$.record(FrameProfiler.scala:80)
	at org.apache.spark.sql.execution.collect.Collector.runSparkJobs(Collector.scala:293)
	at org.apache.spark.sql.execution.collect.Collector.collect(Collector.scala:377)
	at org.apache.spark.sql.execution.collect.Collector$.collect(Collector.scala:128)
	at org.apache.spark.sql.execution.collect.Collector$.collect(Collector.scala:135)
	at org.apache.spark.sql.execution.qrc.InternalRowFormat$.collect(cachedSparkResults.scala:122)
	at org.apache.spark.sql.execution.qrc.InternalRowFormat$.collect(cachedSparkResults.scala:110)
	at org.apache.spark.sql.execution.qrc.InternalRowFormat$.collect(cachedSparkResults.scala:92)
	at org.apache.spark.sql.execution.qrc.ResultCacheManager.$anonfun$computeResult$1(ResultCacheManager.scala:537)
	at com.databricks.spark.util.FrameProfiler$.record(FrameProfiler.scala:80)
	at org.apache.spark.sql.execution.qrc.ResultCacheManager.collectResult$1(ResultCacheManager.scala:529)
	at org.apache.spark.sql.execution.qrc.ResultCacheManager.computeResult(ResultCacheManager.scala:549)
	at org.apache.spark.sql.execution.qrc.ResultCacheManager.$anonfun$getOrComputeResultInternal$1(ResultCacheManager.scala:402)
	at scala.Option.getOrElse(Option.scala:189)
	at org.apache.spark.sql.execution.qrc.ResultCacheManager.getOrComputeResultInternal(ResultCacheManager.scala:395)
	at org.apache.spark.sql.execution.qrc.ResultCacheManager.getOrComputeResult(ResultCacheManager.scala:289)
	at org.apache.spark.sql.execution.SparkPlan.$anonfun$executeCollectResult$1(SparkPlan.scala:506)
	at com.databricks.spark.util.FrameProfiler$.record(FrameProfiler.scala:80)
	at org.apache.spark.sql.execution.SparkPlan.executeCollectResult(SparkPlan.scala:503)
	at org.apache.spark.sql.Dataset.collectResult(Dataset.scala:3453)
	at org.apache.spark.sql.Dataset.$anonfun$collectResult$1(Dataset.scala:3444)
	at org.apache.spark.sql.Dataset.$anonfun$withAction$3(Dataset.scala:4368)
	at org.apache.spark.sql.execution.QueryExecution$.withInternalError(QueryExecution.scala:809)
	at org.apache.spark.sql.Dataset.$anonfun$withAction$2(Dataset.scala:4366)
	at org.apache.spark.sql.execution.SQLExecution$.$anonfun$withCustomExecutionEnv$8(SQLExecution.scala:227)
	at org.apache.spark.sql.execution.SQLExecution$.withSQLConfPropagated(SQLExecution.scala:410)
	at org.apache.spark.sql.execution.SQLExecution$.$anonfun$withCustomExecutionEnv$1(SQLExecution.scala:172)
	at org.apache.spark.sql.SparkSession.withActive(SparkSession.scala:1038)
	at org.apache.spark.sql.execution.SQLExecution$.withCustomExecutionEnv(SQLExecution.scala:122)
	at org.apache.spark.sql.execution.SQLExecution$.withNewExecutionId(SQLExecution.scala:360)
	at org.apache.spark.sql.Dataset.withAction(Dataset.scala:4366)
	at org.apache.spark.sql.Dataset.collectResult(Dataset.scala:3443)
	at com.databricks.backend.daemon.driver.OutputAggregator$.withOutputAggregation0(OutputAggregator.scala:267)
	at com.databricks.backend.daemon.driver.OutputAggregator$.withOutputAggregation(OutputAggregator.scala:101)
	at com.databricks.backend.daemon.driver.PythonDriverLocalBase.generateTableResult(PythonDriverLocalBase.scala:723)
	at com.databricks.backend.daemon.driver.JupyterDriverLocal.computeListResultsItem(JupyterDriverLocal.scala:844)
	at com.databricks.backend.daemon.driver.JupyterDriverLocal$JupyterEntryPoint.addCustomDisplayData(JupyterDriverLocal.scala:263)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:380)
	at py4j.Gateway.invoke(Gateway.java:306)
	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
	at py4j.commands.CallCommand.execute(CallCommand.java:79)
	at py4j.ClientServerConnection.waitForCommands(ClientServerConnection.java:195)
	at py4j.ClientServerConnection.run(ClientServerConnection.java:115)
	at java.lang.Thread.run(Thread.java:750)
Caused by: java.lang.IllegalArgumentException: Expected 1 batch elements but found 0. Expected shape is [1].
	at com.microsoft.azure.synapse.ml.onnx.ONNXUtils$.assertBufferElementsWritten(ONNXUtils.scala:207)
	at com.microsoft.azure.synapse.ml.onnx.ONNXUtils$.loadTensorBuffer(ONNXUtils.scala:168)
	at com.microsoft.azure.synapse.ml.onnx.ONNXUtils$.createTensor(ONNXUtils.scala:106)
	at com.microsoft.azure.synapse.ml.onnx.ONNXRuntime$.$anonfun$applyModel$2(ONNXRuntime.scala:74)
	at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:286)
	at scala.collection.Iterator.foreach(Iterator.scala:943)
	at scala.collection.Iterator.foreach$(Iterator.scala:943)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1431)
	at scala.collection.IterableLike.foreach(IterableLike.scala:74)
	at scala.collection.IterableLike.foreach$(IterableLike.scala:73)
	at scala.collection.AbstractIterable.foreach(Iterable.scala:56)
	at scala.collection.TraversableLike.map(TraversableLike.scala:286)
	at scala.collection.TraversableLike.map$(TraversableLike.scala:279)
	at scala.collection.AbstractTraversable.map(Traversable.scala:108)
	at com.microsoft.azure.synapse.ml.onnx.ONNXRuntime$.$anonfun$applyModel$1(ONNXRuntime.scala:67)
	at scala.collection.Iterator$$anon$10.next(Iterator.scala:461)
	at com.microsoft.azure.synapse.ml.core.utils.CloseableIterator.next(CloseableIterator.scala:11)
	at scala.collection.Iterator$$anon$10.next(Iterator.scala:461)
	at scala.collection.Iterator$$anon$10.next(Iterator.scala:461)
	at scala.collection.Iterator$$anon$11.nextCur(Iterator.scala:486)
	at scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:492)
	at scala.collection.Iterator$$anon$10.hasNext(Iterator.scala:460)
	at org.apache.spark.sql.catalyst.expressions.GeneratedClass$GeneratedIteratorForCodegenStage2.processNext(Unknown Source)
	at org.apache.spark.sql.execution.BufferedRowIterator.hasNext(BufferedRowIterator.java:43)
	at org.apache.spark.sql.execution.WholeStageCodegenExec$$anon$1.hasNext(WholeStageCodegenExec.scala:761)
	at org.apache.spark.sql.execution.collect.UnsafeRowBatchUtils$.encodeUnsafeRows(UnsafeRowBatchUtils.scala:82)
	at org.apache.spark.sql.execution.collect.Collector.$anonfun$processFunc$1(Collector.scala:208)
	at org.apache.spark.scheduler.ResultTask.$anonfun$runTask$3(ResultTask.scala:75)
	at com.databricks.spark.util.ExecutorFrameProfiler$.record(ExecutorFrameProfiler.scala:110)
	at org.apache.spark.scheduler.ResultTask.$anonfun$runTask$1(ResultTask.scala:75)
	at com.databricks.spark.util.ExecutorFrameProfiler$.record(ExecutorFrameProfiler.scala:110)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:55)
	at org.apache.spark.scheduler.Task.doRunTask(Task.scala:174)
	at org.apache.spark.scheduler.Task.$anonfun$run$5(Task.scala:142)
	at com.databricks.unity.EmptyHandle$.runWithAndClose(UCSHandle.scala:125)
	at org.apache.spark.scheduler.Task.$anonfun$run$1(Task.scala:142)
	at com.databricks.spark.util.ExecutorFrameProfiler$.record(ExecutorFrameProfiler.scala:110)
	at org.apache.spark.scheduler.Task.run(Task.scala:97)
	at org.apache.spark.executor.Executor$TaskRunner.$anonfun$run$13(Executor.scala:904)
	at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1713)
	at org.apache.spark.executor.Executor$TaskRunner.$anonfun$run$4(Executor.scala:907)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
	at com.databricks.spark.util.ExecutorFrameProfiler$.record(ExecutorFrameProfiler.scala:110)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:761)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	... 1 more
```

### What component(s) does this bug affect?

- [ ] `area/cognitive`: Cognitive project
- [ ] `area/core`: Core project
- [x] `area/deep-learning`: DeepLearning project
- [ ] `area/lightgbm`: Lightgbm project
- [ ] `area/opencv`: Opencv project
- [ ] `area/vw`: VW project
- [ ] `area/website`: Website
- [ ] `area/build`: Project build system
- [ ] `area/notebooks`: Samples under notebooks folder
- [ ] `area/docker`: Docker usage
- [X] `area/models`: models related issue

### What language(s) does this bug affect?

- [ ] `language/scala`: Scala source code
- [X] `language/python`: Pyspark APIs
- [ ] `language/r`: R APIs
- [ ] `language/csharp`: .NET APIs
- [ ] `language/new`: Proposals for new client languages

### What integration(s) does this bug affect?

- [X] `integrations/synapse`: Azure Synapse integrations
- [ ] `integrations/azureml`: Azure ML integrations
- [ ] `integrations/databricks`: Databricks integrations

**Comment by ANNIKADAHLMANN-8451** [comment]
Any update on this issue?

**Comment by memoryz** [comment]
@ANNIKADAHLMANN-8451 can you attach the converted onnx model here? I can take a look.

**Comment by memoryz** [comment]
@ANNIKADAHLMANN-8451 I looked into the model and the problem is indeed caused by null values. Unfortunately the current implementation does not support null values in the input tensor. To support null values I believe we need support for sparse tensors which wasn't added until onnx 1.10.0, but we currently rely on onnx 1.8.1. Not only that, the java onnxruntime also needs to fully support sparse tensor which it doesn't even in the latest version. The model conversion code also needs to support sparse tensor so that the generated onnx operators can properly deal with sparse input. Additionally, as far as I know, no ONNX op consumes sparse tensors. Given all the above, I don't believe we can support null values in the input tensors. Please consider imputation or dropping null values.
