### ISSUE TITLE
1.02 lightgbm glibc error

### ISSUE THREAD

**Issue by shexuan** [microsoft/SynapseML#2174]
SynapseML version
1.0.2

System information
Language version (e.g. python 3.8, scala 2.12): 3.9.13 | packaged by conda-forge
Scala Version: 2.12
Spark Version (e.g. 3.2.3): 3.1.1
Spark Platform (e.g. Synapse, Databricks): Self hosted on Kubernetes

Describe the problem
Error with environment glibc:
```
24/03/02 12:07:34 INFO ApplicationMaster: Unregistering ApplicationMaster with FAILED (diag message: User class threw exception: java.lang.UnsatisfiedLinkError: /data4/yarn/local/usercache/aa/appcache/application_1704445826670_14757768/container_e37_1704445826670_14757768_01_000001/tmp/mml-natives8055619781671594734/lib_lightgbm.so: /lib64/libm.so.6: version `GLIBC_2.27' not found (required by /data4/yarn/local/usercache/aa/appcache/application_1704445826670_14757768/container_e37_1704445826670_14757768_01_000001/tmp/mml-natives8055619781671594734/lib_lightgbm.so)
	at java.lang.ClassLoader$NativeLibrary.load(Native Method)
	at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1941)
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1824)
	at java.lang.Runtime.load0(Runtime.java:809)
	at java.lang.System.load(System.java:1086)
	at com.microsoft.azure.synapse.ml.core.env.NativeLoader.loadLibraryByName(NativeLoader.java:66)
	at com.microsoft.azure.synapse.ml.lightgbm.LightGBMUtils$.initializeNativeLibrary(LightGBMUtils.scala:33)
	at com.microsoft.azure.synapse.ml.lightgbm.LightGBMBase.train(LightGBMBase.scala:37)
	at com.microsoft.azure.synapse.ml.lightgbm.LightGBMBase.train$(LightGBMBase.scala:36)
	at com.microsoft.azure.synapse.ml.lightgbm.LightGBMClassifier.train(LightGBMClassifier.scala:27)
	at com.microsoft.azure.synapse.ml.lightgbm.LightGBMClassifier.train(LightGBMClassifier.scala:27)
	at org.apache.spark.ml.Predictor.fit(Predictor.scala:151)
	at com.iqiyi.ads.algo.dmp.model_v3.BaseModel.buildLgbModel(BaseModel.scala:171)
	at com.iqiyi.ads.algo.dmp.model_v3.Train.train(Train.scala:37)
	at com.iqiyi.ads.algo.dmp.model_v3.Train.run(Train.scala:43)
	at com.iqiyi.ads.algo.dmp.model_v3.Train$.main(Train.scala:58)
	at com.iqiyi.ads.algo.dmp.model_v3.Train.main(Train.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.spark.deploy.yarn.ApplicationMaster$$anon$2.run(ApplicationMaster.scala:732)
```

**Comment by ranadeepsingh** [comment]
The native LightGBM C++ binaries (lib_lightgbm.so) bundled in SynapseML require GLIBC version 2.27 or higher. Linux environments with older glibc versions (such as CentOS 7 or RHEL 7) are unsupported for compiled C++ dependencies. Upgrading your cluster nodes or container base image to an OS with GLIBC 2.27+ (such as Ubuntu 18.04+, Debian 10+, or RHEL 8+) resolves this issue.
