### ISSUE TITLE
[BUG] Error while using "LightGMB" on Fabric

### ISSUE THREAD

**Issue by promisinganuj** [microsoft/SynapseML#2242]
### SynapseML version

1.0.4

### System information

- **Language version** (e.g. python 3.8, scala 2.12): python 3.10
- **Spark Version** (e.g. 3.2.3): 3.4.1
- **Spark Platform** (e.g. Synapse, Databricks): Fabric

[Runtime 1.2](https://learn.microsoft.com/en-us/fabric/data-engineering/runtime-1-2)

### Describe the problem

I am trying the following tutorial in a Microsoft Fabric notebook:
https://learn.microsoft.com/en-us/fabric/data-science/how-to-use-lightgbm-with-synapseml

The Step 5 of this sample is failing:
```python
from synapse.ml.lightgbm import LightGBMClassifier

model = LightGBMClassifier(
    objective="binary", featuresCol="features", labelCol="Bankrupt?", isUnbalance=True
)
model = model.fit(train_data)
```
Here is the excerpt of the error:

```text
Py4JJavaError                             Traceback (most recent call last)
Cell In[29], line 1
----> 1 model = model.fit(train_data)

File ~/cluster-env/trident_env/lib/python3.10/site-packages/mlflow/utils/autologging_utils/safety.py:573, in safe_patch.<locals>.safe_patch_function(*args, **kwargs)
    571     patch_function.call(call_original, *args, **kwargs)
    572 else:
--> 573     patch_function(call_original, *args, **kwargs)
    575 session.state = "succeeded"
    577 try_log_autologging_event(
    578     AutologgingEventLogger.get_logger().log_patch_function_success,
    579     session,
   (...)
    583     kwargs,
    584 )

File ~/cluster-env/trident_env/lib/python3.10/site-packages/mlflow/utils/autologging_utils/safety.py:252, in with_managed_run.<locals>.patch_with_managed_run(original, *args, **kwargs)
    249     managed_run = create_managed_run()
    251 try:
--> 252     result = patch_function(original, *args, **kwargs)
    253 except (Exception, KeyboardInterrupt):
    254     # In addition to standard Python exceptions, handle keyboard interrupts to ensure
    255     # that runs are terminated if a user prematurely interrupts training execution
    256     # (e.g. via sigint / ctrl-c)
    257     if managed_run:

File ~/cluster-env/trident_env/lib/python3.10/site-packages/mlflow/pyspark/ml/__init__.py:1140, in autolog.<locals>.patched_fit(original, self, *args, **kwargs)
   1138 if t.should_log():
   1139     with _AUTOLOGGING_METRICS_MANAGER.disable_log_post_training_metrics():
-> 1140         fit_result = fit_mlflow(original, self, *args, **kwargs)
   1141     # In some cases the `fit_result` may be an iterator of spark models.
   1142     if should_log_post_training_metrics and isinstance(fit_result, Model):

File ~/cluster-env/trident_env/lib/python3.10/site-packages/mlflow/pyspark/ml/__init__.py:1126, in autolog.<locals>.fit_mlflow(original, self, *args, **kwargs)
   1124 input_training_df = args[0].persist(StorageLevel.MEMORY_AND_DISK)
   1125 _log_pretraining_metadata(estimator, params, input_training_df)
-> 1126 spark_model = original(self, *args, **kwargs)
   1127 _log_posttraining_metadata(estimator, spark_model, params, input_training_df)
   1128 input_training_df.unpersist()

File ~/cluster-env/trident_env/lib/python3.10/site-packages/mlflow/utils/autologging_utils/safety.py:554, in safe_patch.<locals>.safe_patch_function.<locals>.call_original(*og_args, **og_kwargs)
    551         original_result = original(*_og_args, **_og_kwargs)
    552         return original_result
--> 554 return call_original_fn_with_event_logging(_original_fn, og_args, og_kwargs)

File ~/cluster-env/trident_env/lib/python3.10/site-packages/mlflow/utils/autologging_utils/safety.py:489, in safe_patch.<locals>.safe_patch_function.<locals>.call_original_fn_with_event_logging(original_fn, og_args, og_kwargs)
    480 try:
    481     try_log_autologging_event(
    482         AutologgingEventLogger.get_logger().log_original_function_start,
    483         session,
   (...)
    487         og_kwargs,
    488     )
--> 489     original_fn_result = original_fn(*og_args, **og_kwargs)
    491     try_log_autologging_event(
    492         AutologgingEventLogger.get_logger().log_original_function_success,
    493         session,
   (...)
    497         og_kwargs,
    498     )
    499     return original_fn_result

File ~/cluster-env/trident_env/lib/python3.10/site-packages/mlflow/utils/autologging_utils/safety.py:551, in safe_patch.<locals>.safe_patch_function.<locals>.call_original.<locals>._original_fn(*_og_args, **_og_kwargs)
    543 # Show all non-MLflow warnings as normal (i.e. not as event logs)
    544 # during original function execution, even if silent mode is enabled
    545 # (`silent=True`), since these warnings originate from the ML framework
    546 # or one of its dependencies and are likely relevant to the caller
    547 with set_non_mlflow_warnings_behavior_for_current_thread(
    548     disable_warnings=False,
    549     reroute_warnings=False,
    550 ):
--> 551     original_result = original(*_og_args, **_og_kwargs)
    552     return original_result

File /opt/spark/python/lib/pyspark.zip/pyspark/ml/base.py:205, in Estimator.fit(self, dataset, params)
    203         return self.copy(params)._fit(dataset)
    204     else:
--> 205         return self._fit(dataset)
    206 else:
    207     raise TypeError(
    208         "Params must be either a param map or a list/tuple of param maps, "
    209         "but got %s." % type(params)
    210     )

File ~/cluster-env/trident_env/lib/python3.10/site-packages/synapse/ml/lightgbm/LightGBMClassifier.py:2148, in LightGBMClassifier._fit(self, dataset)
   2147 def _fit(self, dataset):
-> 2148     java_model = self._fit_java(dataset)
   2149     return self._create_model(java_model)

File /opt/spark/python/lib/pyspark.zip/pyspark/ml/wrapper.py:378, in JavaEstimator._fit_java(self, dataset)
    375 assert self._java_obj is not None
    377 self._transfer_params_to_java()
--> 378 return self._java_obj.fit(dataset._jdf)

File ~/cluster-env/trident_env/lib/python3.10/site-packages/py4j/java_gateway.py:1322, in JavaMember.__call__(self, *args)
   1316 command = proto.CALL_COMMAND_NAME +\
   1317     self.command_header +\
   1318     args_command +\
   1319     proto.END_COMMAND_PART
   1321 answer = self.gateway_client.send_command(command)
-> 1322 return_value = get_return_value(
   1323     answer, self.gateway_client, self.target_id, self.name)
   1325 for temp_arg in temp_args:
   1326     if hasattr(temp_arg, "_detach"):

File /opt/spark/python/lib/pyspark.zip/pyspark/errors/exceptions/captured.py:169, in capture_sql_exception.<locals>.deco(*a, **kw)
    167 def deco(*a: Any, **kw: Any) -> Any:
    168     try:
--> 169         return f(*a, **kw)
    170     except Py4JJavaError as e:
    171         converted = convert_exception(e.java_exception)

File ~/cluster-env/trident_env/lib/python3.10/site-packages/py4j/protocol.py:326, in get_return_value(answer, gateway_client, target_id, name)
    324 value = OUTPUT_CONVERTER[type](answer[2:], gateway_client)
    325 if answer[1] == REFERENCE_TYPE:
--> 326     raise Py4JJavaError(
    327         "An error occurred while calling {0}{1}{2}.\n".
    328         format(target_id, ".", name), value)
    329 else:
    330     raise Py4JError(
    331         "An error occurred while calling {0}{1}{2}. Trace:\n{3}\n".
    332         format(target_id, ".", name, value))

Py4JJavaError: An error occurred while calling o7876.fit.
: java.lang.Exception: Dataset create from samples call failed in LightGBM with error: Feature (Column_) appears more than one time.
	at com.microsoft.azure.synapse.ml.lightgbm.LightGBMUtils$.validate(LightGBMUtils.scala:18)
	at com.microsoft.azure.synapse.ml.lightgbm.dataset.ReferenceDatasetUtils$.createReferenceDatasetFromSample(ReferenceDatasetUtils.scala:47)
	at com.microsoft.azure.synapse.ml.lightgbm.LightGBMBase.calculateRowStatistics(LightGBMBase.scala:545)
	at com.microsoft.azure.synapse.ml.lightgbm.LightGBMBase.trainOneDataBatch(LightGBMBase.scala:425)
	at com.microsoft.azure.synapse.ml.lightgbm.LightGBMBase.$anonfun$train$2(LightGBMBase.scala:62)
	at com.microsoft.azure.synapse.ml.logging.SynapseMLLogging.logVerb(SynapseMLLogging.scala:163)
	at com.microsoft.azure.synapse.ml.logging.SynapseMLLogging.logVerb$(SynapseMLLogging.scala:160)
	at com.microsoft.azure.synapse.ml.lightgbm.LightGBMClassifier.logVerb(LightGBMClassifier.scala:27)
	at com.microsoft.azure.synapse.ml.logging.SynapseMLLogging.logFit(SynapseMLLogging.scala:153)
	at com.microsoft.azure.synapse.ml.logging.SynapseMLLogging.logFit$(SynapseMLLogging.scala:152)
	at com.microsoft.azure.synapse.ml.lightgbm.LightGBMClassifier.logFit(LightGBMClassifier.scala:27)
	at com.microsoft.azure.synapse.ml.lightgbm.LightGBMBase.train(LightGBMBase.scala:64)
	at com.microsoft.azure.synapse.ml.lightgbm.LightGBMBase.train$(LightGBMBase.scala:36)
	at com.microsoft.azure.synapse.ml.lightgbm.LightGBMClassifier.train(LightGBMClassifier.scala:27)
	at com.microsoft.azure.synapse.ml.lightgbm.LightGBMClassifier.train(LightGBMClassifier.scala:27)
	at org.apache.spark.ml.Predictor.fit(Predictor.scala:114)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:374)
	at py4j.Gateway.invoke(Gateway.java:282)
	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
	at py4j.commands.CallCommand.execute(CallCommand.java:79)
	at py4j.GatewayConnection.run(GatewayConnection.java:238)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

### Code to reproduce issue

```python
from pyspark.sql import SparkSession

# Bootstrap Spark Session
spark = SparkSession.builder.getOrCreate()

from synapse.ml.core.platform import *
from synapse.ml.lightgbm import LightGBMClassifier
from pyspark.ml.feature import VectorAssembler

df = (
    spark.read.format("csv")
    .option("header", True)
    .option("inferSchema", True)
    .load(
        "wasbs://publicwasb@mmlspark.blob.core.windows.net/company_bankruptcy_prediction_data.csv"
    )
)
# print dataset size
print("records read: " + str(df.count()))

train, test = df.randomSplit([0.85, 0.15], seed=1)

feature_cols = df.columns[1:]
featurizer = VectorAssembler(inputCols=feature_cols, outputCol="features")
train_data = featurizer.transform(train)["Bankrupt?", "features"]
test_data = featurizer.transform(test)["Bankrupt?", "features"]

display(train_data.groupBy("Bankrupt?").count())

model = LightGBMClassifier(
    objective="binary", featuresCol="features", labelCol="Bankrupt?", isUnbalance=True
)

model = model.fit(train_data)
```

### What component(s) does this bug affect?

- [ ] `area/cognitive`: Cognitive project
- [ ] `area/core`: Core project
- [ ] `area/deep-learning`: DeepLearning project
- [X] `area/lightgbm`: Lightgbm project
- [ ] `area/opencv`: Opencv project
- [ ] `area/vw`: VW project
- [ ] `area/website`: Website
- [ ] `area/build`: Project build system
- [ ] `area/notebooks`: Samples under notebooks folder
- [ ] `area/docker`: Docker usage
- [ ] `area/models`: models related issue

### What language(s) does this bug affect?

- [ ] `language/scala`: Scala source code
- [X] `language/python`: Pyspark APIs
- [ ] `language/r`: R APIs
- [ ] `language/csharp`: .NET APIs
- [ ] `language/new`: Proposals for new client languages

### What integration(s) does this bug affect?

- [X] `integrations/synapse`: Azure Synapse integrations
- [ ] `integrations/azureml`: Azure ML integrations
- [ ] `integrations/databricks`: Databricks integrations

**Comment by promisinganuj** [comment]
Please refer to https://github.com/microsoft/LightGBM/issues/6492 which was initially raised with LightGBM initially.

**Comment by Illuminae** [comment]
Tagging on to this; I am seeing the same error in the same Fabric Spark runtime.

**Comment by ttruong001** [comment]
I've got the same issue when running the following script on Synapse studio
%%configure -f
{
  "name": "synapseml",
  "conf": {
      "spark.jars.packages": "com.microsoft.azure:synapseml_2.12:1.0.4",
      "spark.jars.repositories": "https://mmlspark.azureedge.net/maven",
      "spark.jars.excludes": "org.scala-lang:scala-reflect,org.apache.spark:spark-tags_2.12,org.scalactic:scalactic_2.12,org.scalatest:scalatest_2.12,com.fasterxml.jackson.core:jackson-databind",
      "spark.yarn.user.classpath.first": "true",
      "spark.sql.parquet.enableVectorizedReader": "false"
  }
}

train, test = (
    spark.read.parquet(
        "wasbs://publicwasb@mmlspark.blob.core.windows.net/BookReviewsFromAmazon10K.parquet"
    )
    .limit(1000)
    .cache()
    .randomSplit([0.8, 0.2])
)

display(train)

from pyspark.ml import Pipeline
from synapse.ml.featurize.text import TextFeaturizer
from synapse.ml.lightgbm import LightGBMRegressor

model = Pipeline(
    stages=[
        TextFeaturizer(inputCol="text", outputCol="features"),
        LightGBMRegressor(featuresCol="features", labelCol="rating"),
    ]
).fit(train)

**Comment by memoryz** [comment]
We're running into the same issue with this configuration:
 "spark.jars.packages": "com.microsoft.azure:synapseml_2.12:0.10.1"

**Comment by mhamilton723** [comment]
Hi All, thank you for your patience. We have tried to get a simple repro of this and found that its something funky is going on with the natives. 

```python
...
.setDataTransferMode("bulk")
``

To work around this for now

**Comment by memoryz** [comment]
> Hi All, thank you for your patience. We have tried to get a simple repro of this and found that its something funky is going on with the natives.
> 
> ```python
> ...
> .setDataTransferMode("bulk")
> ```
> 
> To work around this for now

Confirm this works. Thank you @mhamilton723 for the mitigation.

**Comment by Jens-automl** [comment]
Can you elaborate how to use the workaround. Thank you!

**Comment by denisa-ms** [comment]
from synapse.ml.lightgbm import LightGBMClassifier

model = LightGBMClassifier(
    objective="binary", featuresCol="features", labelCol="Bankrupt?", isUnbalance=True**, dataTransferMode="bulk"**
)

**Comment by ranadeepsingh** [comment]
This is being fixed by #2508, which is open and green in CI.

The root cause is that Spark can surface repeated feature names through the `AttributeGroup` metadata on the features column, and LightGBM rejects a Dataset whose feature names repeat. #2508 de-duplicates the names before they are handed to LightGBM, so the repeated `Column_` entries become `Column_`, `Column__1`, and so on.

Two details worth noting for anyone hitting this:

- The error text in this report comes from `Dataset create from samples`. On current `master` the same root cause surfaces from `Dataset set feature names` instead, because the streaming path now names the reference Dataset. Same cause, different call site.
- De-duplication is done on the name LightGBM actually compares. LightGBM replaces spaces with underscores before checking for duplicates, so `"a b"` and `"a_b"` collide natively even though they are distinct strings in Spark. That case is covered by a regression test.

Leaving this issue open until #2508 merges; it is linked so it will close automatically at that point.

**Comment by ranadeepsingh** [comment]
This failure still reproduces on current `master`, including the changes from microsoft/SynapseML#2508. This report should remain open.

I reproduced it on Fabric Runtime 1.3 with core and LightGBM jars built from `8c7143875c843c649a817cf3e8ba9c7bee23689c`, plus the published `com.microsoft.ml.lightgbm:lightgbmlib:3.3.510`. I checked the loaded native libraries against the bytes in that exact Maven jar rather than assuming that Fabric loaded the requested version.

The smaller reproduction uses **two numerical features with explicitly unique names**, no categorical features, and no barrier execution. It fails on the driver:

```text
Dataset create from samples call failed in LightGBM with error:
Feature (Column_) appears more than one time.
  at ReferenceDatasetUtils.createDatasetFromSamples
  at ReferenceDatasetUtils.createReferenceDatasetFromSample
```

The distinction from microsoft/SynapseML#2508 matters. In [the current reference-dataset code](https://github.com/microsoft/SynapseML/blob/8c7143875c843c649a817cf3e8ba9c7bee23689c/lightgbm/src/main/scala/com/microsoft/azure/synapse/ml/lightgbm/dataset/ReferenceDatasetUtils.scala#L33-L36), native dataset construction happens **before** `setFeatureNamesIfProvided`. The native construction call itself throws, so de-duplicating Spark metadata or supplying unique `slotNames` cannot repair this failing call. The earlier statement that the sampled-construction and set-feature-names failures necessarily share the same metadata cause was too strong.

The name de-duplication fix is still useful for genuinely repeated supplied names. This evidence is not a reason to remove it.

### Reproduction inputs

The executed workload used the following data and estimator settings:

```python
from pyspark.ml.feature import VectorAssembler
from pyspark.sql import SparkSession, functions as F
from synapse.ml.lightgbm import LightGBMRegressor

spark = SparkSession.builder.getOrCreate()
raw = (
    spark.range(100000, numPartitions=16)
    .withColumn("num0", F.randn(751))
    .withColumn("num1", F.randn(752))
    .withColumn("label", F.randn(830))
    .withColumn("is_validation", F.col("id") % 5 == 0)
)
data = (
    VectorAssembler(inputCols=["num0", "num1"], outputCol="features")
    .transform(raw)
    .select("id", "label", "features", "is_validation")
    .repartition(16)
    .cache()
)
try:
    data.count()
    LightGBMRegressor(
        featuresCol="features",
        labelCol="label",
        slotNames=["num0", "num1"],
        categoricalSlotIndexes=[],
        dataTransferMode="streaming",
        useSingleDatasetMode=True,
        useBarrierExecutionMode=False,
        numTasks=16,
        numThreads=2,
        maxStreamingOMPThreads=16,
        numIterations=25,
        seed=731,
        validationIndicatorCol="is_validation",
        earlyStoppingRound=5,
        matrixType="auto",
        verbosity=1,
        timeout=180.0,
    ).fit(data)
finally:
    data.unpersist()
```

The Fabric run used two fixed executors with dynamic allocation and speculation disabled. A separate one-numerical-feature streaming control completed with validation data, two native training ranks, and 100,000 evaluated finite predictions. An 11-feature bulk control also completed. This is not evidence that all streaming inputs fail or that a network setting is the cause.

For native provenance, the loaded Linux library hashes were:

```text
lib_lightgbm.so       c91e863e914ee107814bad0982f33980f5cabdcfe6c12395ccf626a80578e104
lib_lightgbm_swig.so  3fe663bcc6af9d570a01ce28ed8e71aa2abd489771b6ccb4f4fdb437dc8b3e29
```

The native build/runtime cause and a native-only correction still need to be established. This sampled-reference failure is separate from the distributed categorical `SplitInner` crash tracked in microsoft/SynapseML#2697 and from the multicore ingestion reports in microsoft/SynapseML#2333.

**Comment by ranadeepsingh** [comment]
## Fresh Fabric reproduction and process isolation, 2026-09-07

This still reproduces on `8c7143875c843c649a817cf3e8ba9c7bee23689c`, which includes microsoft/SynapseML#2508. A fresh public `LightGBMRegressor.fit()` run on Fabric Runtime 1.3, Spark `3.5.5.5.4.20260807.1`, fails with:

```text
Dataset create from samples call failed in LightGBM with error:
Feature (Column_) appears more than one time.
```

That run used 4,096 synthetic rows, two numerical features, explicit unique slot names `["num0", "num1"]`, no categorical features, streaming transfer, and no barrier execution. Dynamic allocation and speculation were disabled. The first failure is on the driver in `createDatasetFromSamples`, before distributed LightGBM training starts.

### The failure also reproduces without Spark feature metadata

I added a small JNI probe that calls `LGBM_DatasetCreateFromSampledColumn` directly with 64 deterministic sample rows. Each column contains `row + 0.25 * column`, row indexes are `0..63`, and the parameters are:

```text
num_threads=1 min_data_in_leaf=1 min_data_in_bin=1 verbosity=-1
```

The same probe ran inside the Spark driver and in a fresh Java process on that same Fabric host. The fresh process used the driver's `java.home`, the same native jar on its explicit classpath, and `System.load` with the exact two native-library files whose hashes had been checked in the driver.

| Native package and caller | One column | Two columns | Eleven columns |
| --- | --- | --- | --- |
| Published `3.3.510`, Spark driver | Succeeds, but the default name is `Column_`, with no numeric suffix | Native return code `-1`, duplicate `Column_` | Same duplicate-name failure |
| Published `3.3.510`, fresh JVM on the same host | `Column_0` | `Column_0`, `Column_1` | `Column_0` through `Column_10` |
| Source-era `0957ab72` manylinux-compatible reconstruction, Spark driver | Succeeds with the same incorrect `Column_` name | Same duplicate-name failure | Same duplicate-name failure |
| Same reconstruction, fresh JVM on the same host | `Column_0` | `Column_0`, `Column_1` | `Column_0` through `Column_10` |

A further application repeated the published-package probe on newly created Java threads **inside the existing Spark driver JVM**. Those threads produced the same missing numeric suffix and duplicate-name failure. The original calling thread still failed afterward. Moving the call to a fresh Java thread is therefore not a demonstrated workaround; starting a separate JVM changed the result.

The successful fresh-JVM rows above are low-level Dataset-construction controls, not claims that the public distributed estimator completed.

### What this narrows down

The failure does not require duplicated Spark `AttributeGroup` names, user-supplied categorical names, or malformed feature vectors. The direct JNI call has no Spark feature metadata to de-duplicate. The one-column result also explains why a one-feature smoke can succeed while hiding the native name-generation problem.

In the known source-era implementation, [default names are built with `std::stringstream << "Column_" << i`](https://github.com/lightgbm-org/LightGBM/blob/0957ab72f7e46649dc0e48daf15d1c2a9381c6a3/src/io/dataset_loader.cpp#L606-L613). The observed difference now points to the native code's interaction with the Spark driver process. Native symbol binding, C++ stream or locale state, and loaded-library interactions are worth investigating. **These remain hypotheses; this experiment does not identify the responsible component or establish a production fix.**

The two-feature public fit and both process-comparison applications materialized the same numeric workload fingerprint: `count=4096`, `bit_xor(xxhash64(id, label, vector_to_array(features)))=8810333898272871007`.

<details>
<summary>Artifact identity</summary>

Published package and extracted native pair:

```text
lightgbmlib-3.3.510.jar
f2b1b13172699832594303ab4c04f3bc8fc2d24737e3e8c11d98d69a88c09272
lib_lightgbm.so
c91e863e914ee107814bad0982f33980f5cabdcfe6c12395ccf626a80578e104
lib_lightgbm_swig.so
3fe663bcc6af9d570a01ce28ed8e71aa2abd489771b6ccb4f4fdb437dc8b3e29
```

The independently rebuilt control jar:

```text
lightgbmlib-diagnostic-0957ab72-unpatched-manylinux228-linux-x86_64.jar
c92caff2324236fbace50e409e8d43bdfcb1cc2fe46bdcd3f0aa3bce1831713e
```

The compiled probe packages:

```text
fabric-reliability-probes.jar
782860dcb46378ffe34c371f97722f9318d6fa46afc75b3d52d198dcecd2c0e2
fabric-reliability-probes-v2.jar
d7d7d1903ddbf4f760a9cbffefe4d7217056ea3ac39a739881b74a80c8669365
```

The source-era reconstruction is not claimed to be the published package's exact source revision. The same core and LightGBM Scala jars from `8c714387` were used throughout; their hashes are recorded in [the fresh native A/B evidence](https://github.com/microsoft/SynapseML/issues/2697#issuecomment-5572446410).

</details>

All four scratch lakehouses were deleted successfully, and the scenario code, jar digests, and downloaded logs are retained. Please keep this separate from the categorical `SplitInner` defect in microsoft/SynapseML#2697 and from the supplied-name de-duplication handled by microsoft/SynapseML#2508.
