### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by SGA-daiki-kimura** [microsoft/SynapseML#2274]
### SynapseML version

1.0.5

### System information

- **Language version** (e.g. python 3.8, scala 2.12):Python 3.11.0rc1
- **Spark Version** (e.g. 3.2.3):3.5.0
- **Spark Platform** (e.g. Synapse, Databricks):Databricks

### Describe the problem

**Expected Behavior**:
The SAR model should accept `userId`  and `itemId` as an integer type as specified in the documentation.

**Actual Behavior**:
The SAR model only works when `userId` and `itemId`  are cast to `DoubleType`. This is contrary to the documentation which states that `userId` should be within the integer value range.

### Code to reproduce issue

import requests
import zipfile
import io
import pandas as pd
from pyspark.sql import SparkSession
from pyspark.sql.types import DoubleType, LongType
from synapse.ml.recommendation import SAR

# Sparkセッションの作成
spark = SparkSession.builder.appName("SmartAdaptiveRecommendations").getOrCreate()

# 1. URLからデータをダウンロードする
url = "http://files.grouplens.org/datasets/movielens/ml-25m.zip"
response = requests.get(url)

# 2. ダウンロードしたzipファイルを解凍する
with zipfile.ZipFile(io.BytesIO(response.content)) as z:
    # 3. 解凍したcsvファイルをpandasのDataFrameとして読み込む
    with z.open('ml-25m/ratings.csv') as csvfile:
        pdf_ratings = pd.read_csv(csvfile)
    with z.open('ml-25m/links.csv') as csvfile:
        pdf_links = pd.read_csv(csvfile)
    with z.open('ml-25m/movies.csv') as csvfile:
        pdf_movies = pd.read_csv(csvfile)
    with z.open('ml-25m/tags.csv') as csvfile:
        pdf_tags = pd.read_csv(csvfile)

# 明示的評価を暗黙的評価にするために全部に1.0を代入する
pdf_ratings["rating"] = 1.0

# pandas DataFrameをSpark DataFrameに変換
spark_df_ratings = spark.createDataFrame(pdf_ratings)

# 各列のデータ型を表示して確認
print("Before casting:")
spark_df_ratings.printSchema()

# データ型を明示的に変換
spark_df_ratings = spark_df_ratings.withColumn("userId", spark_df_ratings["userId"].cast(LongType()))
spark_df_ratings = spark_df_ratings.withColumn("movieId", spark_df_ratings["movieId"].cast(LongType()))
spark_df_ratings = spark_df_ratings.withColumn("rating", spark_df_ratings["rating"].cast(DoubleType()))
spark_df_ratings = spark_df_ratings.withColumn("timestamp", spark_df_ratings["timestamp"].cast(LongType()))

# 各列のデータ型を再度表示して確認
print("After casting:")
spark_df_ratings.printSchema()

# SARモデルの設定
sar = SAR(
    userCol="userId",
    itemCol="movieId",
    ratingCol="rating",
    timeCol="timestamp",
    implicitPrefs=True,
    activityTimeFormat="epoch"
)

# モデルのトレーニング
model = sar.fit(spark_df_ratings)

### Other info / logs

```
Py4JJavaError: An error occurred while calling o629.fit.
: java.lang.ClassCastException: java.lang.Long cannot be cast to java.lang.Double
    at scala.runtime.BoxesRunTime.unboxToDouble(BoxesRunTime.java:116)
    at org.apache.spark.sql.Row.getDouble(Row.scala:275)
    at org.apache.spark.sql.Row.getDouble$(Row.scala:275)
    at org.apache.spark.sql.catalyst.expressions.GenericRow.getDouble(rows.scala:28)
    at com.microsoft.azure.synapse.ml.recommendation.SAR.calculateUserItemAffinities(SAR.scala:99)
    at com.microsoft.azure.synapse.ml.recommendation.SAR.$anonfun$fit$1(SAR.scala:69)
    at com.microsoft.azure.synapse.ml.logging.SynapseMLLogging.logVerb(SynapseMLLogging.scala:163)
    at com.microsoft.azure.synapse.ml.logging.SynapseMLLogging.logVerb$(SynapseMLLogging.scala:160)
    at com.microsoft.azure.synapse.ml.recommendation.SAR.logVerb(SAR.scala:36)
    at com.microsoft.azure.synapse.ml.logging.SynapseMLLogging.logFit(SynapseMLLogging.scala:153)
    at com.microsoft.azure.synapse.ml.logging.SynapseMLLogging.logFit$(SynapseMLLogging.scala:152)
    at com.microsoft.azure.synapse.ml.recommendation.SAR.logFit(SAR.scala:36)
    at com.microsoft.azure.synapse.ml.recommendation.SAR.fit(SAR.scala:75)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
    at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:397)
    at py4j.Gateway.invoke(Gateway.java:306)
    at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
    at py4j.commands.CallCommand.execute(CallCommand.java:79)
    at py4j.ClientServerConnection.waitForCommands(ClientServerConnection.java:199)
    at py4j.ClientServerConnection.run(ClientServerConnection.java:119)
    at java.lang.Thread.run(Thread.java:750)

### What component(s) does this bug affect?

- [ ] `area/cognitive`: Cognitive project
- [X] `area/core`: Core project
- [ ] `area/deep-learning`: DeepLearning project
- [ ] `area/lightgbm`: Lightgbm project
- [ ] `area/opencv`: Opencv project
- [ ] `area/vw`: VW project
- [ ] `area/website`: Website
- [ ] `area/build`: Project build system
- [ ] `area/notebooks`: Samples under notebooks folder
- [ ] `area/docker`: Docker usage
- [ ] `area/models`: models related issue

### What language(s) does this bug affect?

- [ ] `language/scala`: Scala source code
- [X] `language/python`: Pyspark APIs
- [ ] `language/r`: R APIs
- [ ] `language/csharp`: .NET APIs
- [ ] `language/new`: Proposals for new client languages

### What integration(s) does this bug affect?

- [ ] `integrations/synapse`: Azure Synapse integrations
- [ ] `integrations/azureml`: Azure ML integrations
- [X] `integrations/databricks`: Databricks integrations

**Comment by ranadeepsingh** [comment]
Thanks for reporting this. The fix has now been merged to `master` in PR #2594: https://github.com/microsoft/SynapseML/pull/2594

SAR now uses lossless typed identifier mappings and includes regression coverage for integer and `LongType` user/item identifiers, eliminating the unsafe cast that caused this failure.

PR #2594 merged after SynapseML v1.1.3 was published, so the fix is not part of v1.1.3. It will be available in the next SynapseML release after v1.1.3. Closing this issue as fixed on `master`.
