### ISSUE TITLE
ClassCastException while training LightGBMRegressor [Urgent]

### ISSUE THREAD

**Issue by dimple-bansal** [microsoft/SynapseML#629]
Unable to train and fit LightGBMRegressor (tried vectorising feature columns using both mllib Vector Assembler and mmlspark's featurizeData, both resulting in below error)
@imatiach-msft @mhamilton723 

`java.lang.ClassCastException: com.microsoft.ml.spark.LightGBMBooster cannot be cast to com.microsoft.ml.spark.LightGBMBooster
  at com.microsoft.ml.spark.LightGBMBase$class.train(LightGBMBase.scala:51)
  at ### com.microsoft.ml.spark.LightGBMRegressor.train(LightGBMRegressor.scala:35)
  at com.microsoft.ml.spark.LightGBMRegressor.train(LightGBMRegressor.scala:35)
  at org.apache.spark.ml.Predictor.fit(Predictor.scala:118)`

**Comment by imatiach-msft** [comment]
@dimple-bansal sorry about the trouble you are having. What version of mmlspark are you using?  I was pretty sure this was fixed when adding the @SerialVersionUID to LightGBMBooster:
https://github.com/Azure/mmlspark/blob/master/src/main/scala/com/microsoft/ml/spark/lightgbm/LightGBMBooster.scala#L14
which was fixed 10 months ago:
https://github.com/Azure/mmlspark/commit/702b165c84f844da6d10c93f8c5bbfc47d939a81

**Comment by dimple-bansal** [comment]
We are using MML-Spark 0.17, the release from April 24. 
This release seems to contain the @serialversionuid addition but still ClassCastExpection seems to exists.

**Comment by imatiach-msft** [comment]
@dimple-bansal actually, this issue does seem to be different, the error then was:
```
java.io.InvalidClassException: com.microsoft.ml.spark.LightGBMBooster; local class incompatible: stream classdesc serialVersionUID = -6123404490847323315, local class serialVersionUID = 9020853188419181008
```
See relevant issue:
https://github.com/Azure/mmlspark/issues/387
And bug fix:
https://github.com/Azure/mmlspark/pull/388

**Comment by imatiach-msft** [comment]
@dimple-bansal the error message doesn't make sense to me, as it is saying the booster can't be cast to itself, it looks like it is failing in the reduce step in the v0.17 version of the code:
https://github.com/Azure/mmlspark/blob/v0.17/src/lightgbm/src/main/scala/LightGBMBase.scala#L51
The error doesn't make sense to me because the code is trying to cast a "com.microsoft.ml.spark.LightGBMBooster" to a "com.microsoft.ml.spark.LightGBMBooster" and failing, when the latter clearly is the same type as the former.

**Comment by imatiach-msft** [comment]
what version of spark are you running?  maybe there is something weird going on with the kryo serializaton (Encoders.kryo[LightGBMBooster])

**Comment by imatiach-msft** [comment]
not sure if this is relevant, seems like a similar error to what we are seeing with kryo serialization: https://github.com/EsotericSoftware/kryo/issues/160

**Comment by dimple-bansal** [comment]
Running on spark version of 2.4.3 and scala version of 2.11.12.

**Comment by yaochitc** [comment]
Hi,I also face the same problem, is this sovled?

**Comment by imatiach-msft** [comment]
@yaochitc what version of mmlspark are you using, and also spark and scala?  I'm pretty sure this was fixed two years ago.

**Comment by ranadeepsingh** [comment]
Thank you for the report and follow-up. The serialization defect was fixed in later SynapseML versions, while this case targets Spark 2.4/MMLSpark-era artifacts. Closing as resolved; please file a fresh issue if it appears on 1.1.3.
