### ISSUE TITLE
Error with sparse matrix

### ISSUE THREAD

**Issue by congnt-dsv** [microsoft/SynapseML#777]
I have to run a sparse matrix (1.1M x 16M)
I just can run with normal LightGBM.
But when I run with lightGBM & MMLSPARK, there was have error: 
MML version: mmlspark_2.11:0.18.1

```
20/01/03 12:27:21 WARN org.apache.spark.scheduler.TaskSetManager: Lost task 3.0 in stage 3.0 (TID 10, cluster-aaa.internal, executor 2): java.lang.Exception: Dataset create call failed in LightGBM with error: Check failed: buffer_size >= 0 at /__w/1/s/src/io/dataset_loader.cpp, line 687 .
    at com.microsoft.ml.spark.lightgbm.LightGBMUtils$.validate(LightGBMUtils.scala:31)
    at com.microsoft.ml.spark.lightgbm.LightGBMUtils$.generateSparseDataset(LightGBMUtils.scala:243)
    at com.microsoft.ml.spark.lightgbm.TrainUtils$.generateDataset(TrainUtils.scala:51)
    at com.microsoft.ml.spark.lightgbm.TrainUtils$.translate(TrainUtils.scala:233)
    at com.microsoft.ml.spark.lightgbm.TrainUtils$.trainLightGBM(TrainUtils.scala:385)
    at com.microsoft.ml.spark.lightgbm.LightGBMBase$$anonfun$6.apply(LightGBMBase.scala:145)
    at com.microsoft.ml.spark.lightgbm.LightGBMBase$$anonfun$6.apply(LightGBMBase.scala:145)
    at org.apache.spark.sql.execution.MapPartitionsExec$$anonfun$5.apply(objects.scala:188)
    at org.apache.spark.sql.execution.MapPartitionsExec$$anonfun$5.apply(objects.scala:185)
    at org.apache.spark.rdd.RDD$$anonfun$mapPartitionsInternal$1$$anonfun$apply$24.apply(RDD.scala:836)
    at org.apache.spark.rdd.RDD$$anonfun$mapPartitionsInternal$1$$anonfun$apply$24.apply(RDD.scala:836)
    at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:52)
    at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:324)
    at org.apache.spark.rdd.RDD.iterator(RDD.scala:288)
    at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:52)
    at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:324)
    at org.apache.spark.rdd.RDD.iterator(RDD.scala:288)
    at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:90)
    at org.apache.spark.scheduler.Task.run(Task.scala:123)
    at org.apache.spark.executor.Executor$TaskRunner$$anonfun$10.apply(Executor.scala:408)
    at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1360)
    at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:414)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
    at java.lang.Thread.run(Thread.java:748)

```

**Comment by ranadeepsingh** [comment]
Thank you for reporting this issue! The native LightGBM C++ buffer size overflow (`dataset_loader.cpp`) when creating datasets with large sparse matrices was resolved by upgrading the native LightGBM runtime to LightGBM 3.x/4.x and refactoring sparse dataset construction. This fix is included in published SynapseML releases (v1.0.0 and later). We are closing this issue as fixed in published releases.
